// Generated by ahead. Do not edit.
export interface ReadPort { read(model:string,identity:object):Promise<Record<string,unknown>|null>; querySpec(model:string,query:object):Promise<Record<string,unknown>[]>; related(model:string,identity:object,relation:string):Promise<Record<string,unknown>|null>; referencing(model:string,identity:object,source:string,relation:string):Promise<Record<string,unknown>[]>; }
export interface MutatePort { mutate(value:object):Promise<number>; }
export interface WritePort extends ReadPort { direct(operation:object):Promise<void>; }
export interface LivePort extends ReadPort { watch(model:string,where:Record<string,unknown>,listener:(rows:Record<string,unknown>[])=>void,onError?:(error:unknown)=>void):()=>void; syncState(model:string,identity:object):Promise<unknown>; }
export const schema = {"clientPolicies":[],"enums":[{"name":"Status","values":["open","closed","archived"]}],"models":[{"fields":[{"name":"id","nullable":false,"type":{"kind":"scalar","name":"string"}},{"name":"title","nullable":false,"type":{"kind":"scalar","name":"string"}},{"name":"state","nullable":false,"type":{"kind":"enum","name":"Status"}},{"name":"note","nullable":true,"type":{"kind":"scalar","name":"string"}}],"identity":["id"],"name":"Todo","relations":[],"unique":[],"version":2},{"fields":[{"name":"tenantId","nullable":false,"type":{"kind":"scalar","name":"string"}},{"name":"id","nullable":false,"type":{"kind":"scalar","name":"string"}},{"name":"title","nullable":false,"type":{"kind":"scalar","name":"string"}}],"identity":["tenantId","id"],"name":"Project","relations":[],"unique":[],"version":1}],"prerequisites":[],"requirements":[]} as const;
export type MutationName = string;
export interface PendingMutation { ordinal:number; name:MutationName; phase:'queued'|'frozen'; prerequisites:{key:string;state:'ready'|'pending'|'failed'}[]; diverged?:boolean; }
export interface Rejection { ordinal:number; code:string; [key:string]:unknown; }
export interface SyncState { pending:PendingMutation[]; rejections:Rejection[]; }
export type Status = "open" | "closed" | "archived";
export interface Todo {
 id: string;
 title: string;
 state: Status;
 note: string | null;
}
export interface TodoIdentity {
 id: string;
}
export interface TodoPatch {
 title?: string;
 state?: Status;
 note?: string | null;
}
export function decodeTodo(row:Record<string,unknown>):Todo { return {
 id: row.id as string,
 title: row.title as string,
 state: row.state as Status,
 note: row.note == null ? null : row.note as string,
}; }
export function encodeTodo(value:Todo):Record<string,unknown> { return {
 id: value.id,
 title: value.title,
 state: value.state,
 note: value.note == null ? null : value.note,
}; }
export function encodeTodoIdentity(value:TodoIdentity):Record<string,unknown> { return {
 id: value.id,
}; }
export function encodeTodoPatch(value:TodoPatch):Record<string,unknown> { return {
 ...(value.title !== undefined ? { title: value.title } : {}),
 ...(value.state !== undefined ? { state: value.state } : {}),
 ...(value.note !== undefined ? { note: value.note == null ? null : value.note } : {}),
}; }
export function encodeTodoWhere(value:Partial<Todo>):Record<string,unknown> { return {
 ...(value.id !== undefined ? { id: value.id } : {}),
 ...(value.title !== undefined ? { title: value.title } : {}),
 ...(value.state !== undefined ? { state: value.state } : {}),
 ...(value.note !== undefined ? { note: value.note == null ? null : value.note } : {}),
}; }
export interface Project {
 tenantId: string;
 id: string;
 title: string;
}
export interface ProjectIdentity {
 tenantId: string;
 id: string;
}
export interface ProjectPatch {
 title?: string;
}
export function decodeProject(row:Record<string,unknown>):Project { return {
 tenantId: row.tenantId as string,
 id: row.id as string,
 title: row.title as string,
}; }
export function encodeProject(value:Project):Record<string,unknown> { return {
 tenantId: value.tenantId,
 id: value.id,
 title: value.title,
}; }
export function encodeProjectIdentity(value:ProjectIdentity):Record<string,unknown> { return {
 tenantId: value.tenantId,
 id: value.id,
}; }
export function encodeProjectPatch(value:ProjectPatch):Record<string,unknown> { return {
 ...(value.title !== undefined ? { title: value.title } : {}),
}; }
export function encodeProjectWhere(value:Partial<Project>):Record<string,unknown> { return {
 ...(value.tenantId !== undefined ? { tenantId: value.tenantId } : {}),
 ...(value.id !== undefined ? { id: value.id } : {}),
 ...(value.title !== undefined ? { title: value.title } : {}),
}; }
export class TodoModel<P extends ReadPort=ReadPort> { readonly port:P; constructor(port:P) { this.port=port; }
 async get(identity:TodoIdentity):Promise<Todo|null> { const row=await this.port.read('Todo',encodeTodoIdentity(identity)); return row===null ? null : decodeTodo(row); }
 async query(options:{where?:Partial<Todo>;orderBy?:{field:'id' | 'title' | 'note';direction:'ascending'|'descending'}[];limit?:number}={}):Promise<Todo[]> { return (await this.port.querySpec('Todo',{filter:encodeTodoWhere(options.where??{}),orderBy:options.orderBy??[],...(options.limit===undefined?{}:{limit:options.limit})})).map(decodeTodo); }
}
export class TodoLiveModel extends TodoModel<LivePort> {
 watch(options:{where?:Partial<Todo>}, listener:(rows:Todo[])=>void, onError?:(error:unknown)=>void):()=>void { return this.port.watch('Todo',encodeTodoWhere(options.where??{}),(rows)=>listener(rows.map(decodeTodo)),onError); }
 /** This record's sync state: its pending mutations and retained rejections. Local only. */
 async syncState(identity:TodoIdentity):Promise<SyncState> { return (await this.port.syncState('Todo',encodeTodoIdentity(identity))) as SyncState; }
}
export class TodoTxModel extends TodoModel<WritePort> {
 create(value:Todo):Promise<void> { return this.port.direct({model:'Todo',op:'create',identity:encodeTodoIdentity(value),values:encodeTodoPatch(value)}); }
 update(identity:TodoIdentity, patch:TodoPatch):Promise<void> { return this.port.direct({model:'Todo',op:'update',identity:encodeTodoIdentity(identity),values:encodeTodoPatch(patch)}); }
 delete(identity:TodoIdentity):Promise<void> { return this.port.direct({model:'Todo',op:'delete',identity:encodeTodoIdentity(identity)}); }
}
export class ProjectModel<P extends ReadPort=ReadPort> { readonly port:P; constructor(port:P) { this.port=port; }
 async get(identity:ProjectIdentity):Promise<Project|null> { const row=await this.port.read('Project',encodeProjectIdentity(identity)); return row===null ? null : decodeProject(row); }
 async query(options:{where?:Partial<Project>;orderBy?:{field:'tenantId' | 'id' | 'title';direction:'ascending'|'descending'}[];limit?:number}={}):Promise<Project[]> { return (await this.port.querySpec('Project',{filter:encodeProjectWhere(options.where??{}),orderBy:options.orderBy??[],...(options.limit===undefined?{}:{limit:options.limit})})).map(decodeProject); }
}
export class ProjectLiveModel extends ProjectModel<LivePort> {
 watch(options:{where?:Partial<Project>}, listener:(rows:Project[])=>void, onError?:(error:unknown)=>void):()=>void { return this.port.watch('Project',encodeProjectWhere(options.where??{}),(rows)=>listener(rows.map(decodeProject)),onError); }
 /** This record's sync state: its pending mutations and retained rejections. Local only. */
 async syncState(identity:ProjectIdentity):Promise<SyncState> { return (await this.port.syncState('Project',encodeProjectIdentity(identity))) as SyncState; }
}
export class ProjectTxModel extends ProjectModel<WritePort> {
 create(value:Project):Promise<void> { return this.port.direct({model:'Project',op:'create',identity:encodeProjectIdentity(value),values:encodeProjectPatch(value)}); }
 update(identity:ProjectIdentity, patch:ProjectPatch):Promise<void> { return this.port.direct({model:'Project',op:'update',identity:encodeProjectIdentity(identity),values:encodeProjectPatch(patch)}); }
 delete(identity:ProjectIdentity):Promise<void> { return this.port.direct({model:'Project',op:'delete',identity:encodeProjectIdentity(identity)}); }
}
/** Type-level Action contracts; runtime binding arrives with the Action engine. */
export interface ActionError extends Error { readonly code: string; }
export type ActionStatus = 'pending' | 'succeeded' | 'failed';
export type ActionOutcome<T> = { result: T; error: null } | { result: undefined; error: ActionError };
export interface ActionCall<T> { readonly status: ActionStatus; wait(): Promise<ActionOutcome<T>>; }
export type TodoCreate = Todo;
export type TodoUpdate<K extends keyof TodoPatch = keyof TodoPatch> = TodoIdentity & Partial<Pick<TodoPatch, K>>;
export type TodoDelete = TodoIdentity;
export type ProjectCreate = Project;
export type ProjectUpdate<K extends keyof ProjectPatch = keyof ProjectPatch> = ProjectIdentity & Partial<Pick<ProjectPatch, K>>;
export type ProjectDelete = ProjectIdentity;
export interface AddTodoInput {
 todo: TodoCreate;
 patch?: TodoUpdate<"title"> | null;
 gone: TodoDelete[];
 status: Status | null;
 tags: string[];
}
export interface AddTodoOutput {
 todo: Todo;
 patch: Todo | null;
 gone: TodoIdentity[];
 relatedTodo: Todo | null;
 matches: Todo[];
 count: number;
 state: Status | null;
}
export interface DeleteTodoInput {
 todo: TodoDelete;
}
export interface DeleteTodoOutput {
 todo: TodoIdentity;
}
export interface GetTodosInput {
}
export interface GetTodosOutput {
 todos: Todo[];
}
export interface LinkInput {
 project: ProjectCreate;
}
export interface LinkOutput {
 project: Project;
 relatedProject: Project | null;
}
export interface PingInput {
}
export type PingOutput = void;
export interface RemoveTodoInput {
 todo: TodoDelete;
}
export interface RemoveTodoOutput {
 todo: TodoIdentity;
}
export interface SearchInput {
 query: string | null;
}
export type SearchOutput = void;
export interface SendEmailInput {
 to: string;
 subject: string;
 body: string;
}
export type SendEmailOutput = void;
export interface ActionTxModels {
 todo: Pick<TodoTxModel, 'get' | 'query' | 'create' | 'update' | 'delete'>;
 project: Pick<ProjectTxModel, 'get' | 'query' | 'create' | 'update' | 'delete'>;
}
export interface ActionModels {
 todo: ActionTxModels['todo'] & Pick<TodoLiveModel, 'watch'>;
 project: ActionTxModels['project'] & Pick<ProjectLiveModel, 'watch'>;
}
export interface ActionTransactionContract { readonly models: ActionTxModels; }
export interface ActionClientContract {
 readonly models: ActionModels;
 transaction<T>(body: (tx: ActionTransactionContract) => Promise<T>): Promise<T>;
 readonly actions: {
  addTodo(args: AddTodoInput): Promise<ActionCall<AddTodoOutput>>;
  deleteTodo(args: DeleteTodoInput): Promise<ActionCall<DeleteTodoOutput>>;
  getTodos(args: GetTodosInput): Promise<ActionCall<GetTodosOutput>>;
  link(args: LinkInput): Promise<ActionCall<LinkOutput>>;
  ping(args: PingInput): Promise<ActionCall<PingOutput>>;
  removeTodo(args: RemoveTodoInput): Promise<ActionCall<RemoveTodoOutput>>;
  search(args: SearchInput): Promise<ActionCall<SearchOutput>>;
  sendEmail(args: SendEmailInput): Promise<ActionCall<SendEmailOutput>>;
  call: {
   addTodo(args: AddTodoInput): Promise<AddTodoOutput>;
   deleteTodo(args: DeleteTodoInput): Promise<DeleteTodoOutput>;
   getTodos(args: GetTodosInput): Promise<GetTodosOutput>;
   link(args: LinkInput): Promise<LinkOutput>;
   ping(args: PingInput): Promise<PingOutput>;
   removeTodo(args: RemoveTodoInput): Promise<RemoveTodoOutput>;
   search(args: SearchInput): Promise<SearchOutput>;
   sendEmail(args: SendEmailInput): Promise<SendEmailOutput>;
  };
 };
}
export class Mutate { readonly port:MutatePort; constructor(port:MutatePort) { this.port=port; }
}
export interface LiveModels { todo:TodoLiveModel; project:ProjectLiveModel; }
export function liveModels(port:LivePort):LiveModels { return { todo:new TodoLiveModel(port), project:new ProjectLiveModel(port) }; }
export interface TxModels { todo:TodoTxModel; project:ProjectTxModel; }
export function txModels(port:WritePort):TxModels { return { todo:new TodoTxModel(port), project:new ProjectTxModel(port) }; }
export class GeneratedTransaction { readonly transaction:WritePort; readonly models:TxModels; constructor(transaction:WritePort) { this.transaction=transaction; this.models=txModels(transaction); } }
