// Generated by axton. Do not edit.
import 'dart:convert';
import 'package:axton/axton.dart';
export 'package:axton/axton.dart' show RuntimeConnection, SyncServer;
class Present<T> { final T value; const Present(this.value); }
final Map<String,dynamic> schema = jsonDecode(r'''{"clientPolicies":[],"enums":[{"name":"Status","values":["open","closed","archived"]}],"models":[{"fields":[{"name":"id","nullable":false,"type":{"kind":"scalar","name":"string"}},{"name":"title","nullable":false,"type":{"kind":"scalar","name":"string"}},{"name":"state","nullable":false,"type":{"kind":"enum","name":"Status"}},{"name":"note","nullable":true,"type":{"kind":"scalar","name":"string"}}],"identity":["id"],"name":"Todo","relations":[],"unique":[],"version":2},{"fields":[{"name":"tenantId","nullable":false,"type":{"kind":"scalar","name":"string"}},{"name":"id","nullable":false,"type":{"kind":"scalar","name":"string"}},{"name":"title","nullable":false,"type":{"kind":"scalar","name":"string"}}],"identity":["tenantId","id"],"name":"Project","relations":[],"unique":[],"version":1}],"prerequisites":[],"requirements":[]}''') as Map<String,dynamic>;
enum Status { open, closed, archived }
class Todo {
 final String id;
 final String title;
 final Status state;
 final String? note;
 const Todo({required this.id,required this.title,required this.state,required this.note});
 Map<String,dynamic> toRecord() => {
 'id': id,
 'title': title,
 'state': state.name,
 'note': note == null ? null : note!,
 };
 factory Todo.fromRecord(Map<String,dynamic> row) => Todo(
 id: row['id'] as String,
 title: row['title'] as String,
 state: Status.values.byName(row['state'] as String),
 note: row['note'] == null ? null : row['note'] as String,
 );
 TodoIdentity get identity => TodoIdentity(id: id);
}
class TodoIdentity {
 final String id;
 const TodoIdentity({required this.id});
 Map<String,dynamic> toRecord() => {
 'id': id,
 };
 factory TodoIdentity.fromRecord(Map<String,dynamic> row) => TodoIdentity(
 id: row['id'] as String,
 );
}
class TodoPatch {
 final Present<String>? title;
 final Present<Status>? state;
 final Present<String?>? note;
 const TodoPatch({this.title,this.state,this.note});
 Map<String,dynamic> toRecord() => {
 if (title != null) 'title': title!.value,
 if (state != null) 'state': state!.value.name,
 if (note != null) 'note': note!.value == null ? null : note!.value!,
 };
}
class Project {
 final String tenantId;
 final String id;
 final String title;
 const Project({required this.tenantId,required this.id,required this.title});
 Map<String,dynamic> toRecord() => {
 'tenantId': tenantId,
 'id': id,
 'title': title,
 };
 factory Project.fromRecord(Map<String,dynamic> row) => Project(
 tenantId: row['tenantId'] as String,
 id: row['id'] as String,
 title: row['title'] as String,
 );
 ProjectIdentity get identity => ProjectIdentity(tenantId: tenantId,id: id);
}
class ProjectIdentity {
 final String tenantId;
 final String id;
 const ProjectIdentity({required this.tenantId,required this.id});
 Map<String,dynamic> toRecord() => {
 'tenantId': tenantId,
 'id': id,
 };
 factory ProjectIdentity.fromRecord(Map<String,dynamic> row) => ProjectIdentity(
 tenantId: row['tenantId'] as String,
 id: row['id'] as String,
 );
}
class ProjectPatch {
 final Present<String>? title;
 const ProjectPatch({this.title});
 Map<String,dynamic> toRecord() => {
 if (title != null) 'title': title!.value,
 };
}
class TodoFilter {
 final Present<String>? id;
 final Present<String>? title;
 final Present<Status>? state;
 final Present<String?>? note;
 const TodoFilter({this.id,this.title,this.state,this.note});
 Map<String,dynamic> toRecord()=>{
 if(id!=null)'id':id!.value,
 if(title!=null)'title':title!.value,
 if(state!=null)'state':state!.value.name,
 if(note!=null)'note':note!.value == null ? null : note!.value!,
};
}
enum TodoOrderField {byId('id'),byTitle('title'),byNote('note'); final String wireName; const TodoOrderField(this.wireName);}
class TodoOrder { final TodoOrderField field; final bool descending; const TodoOrder(this.field,{this.descending=false}); Map<String,dynamic> toRecord()=>{'field':field.wireName,'direction':descending?'descending':'ascending'}; }
class ProjectFilter {
 final Present<String>? tenantId;
 final Present<String>? id;
 final Present<String>? title;
 const ProjectFilter({this.tenantId,this.id,this.title});
 Map<String,dynamic> toRecord()=>{
 if(tenantId!=null)'tenantId':tenantId!.value,
 if(id!=null)'id':id!.value,
 if(title!=null)'title':title!.value,
};
}
enum ProjectOrderField {byTenantId('tenantId'),byId('id'),byTitle('title'); final String wireName; const ProjectOrderField(this.wireName);}
class ProjectOrder { final ProjectOrderField field; final bool descending; const ProjectOrder(this.field,{this.descending=false}); Map<String,dynamic> toRecord()=>{'field':field.wireName,'direction':descending?'descending':'ascending'}; }
class TodoModel { final ReadPort port; TodoModel(this.port);
 Future<Todo?> get(TodoIdentity identity) async { final row=await port.read('Todo',identity.toRecord()); return row == null ? null : Todo.fromRecord(row); }
 Future<List<Todo>> query({TodoFilter? where,List<TodoOrder> orderBy=const [],int? limit}) async => (await port.querySpec('Todo',{'filter':where?.toRecord()??{},'orderBy':orderBy.map((o)=>o.toRecord()).toList(),if(limit!=null)'limit':limit})).map(Todo.fromRecord).toList();
}
class TodoLiveModel extends TodoModel { final Client client; TodoLiveModel(this.client) : super(client);
 Stream<List<Todo>> watch({TodoFilter? where}) => client.watch('Todo', where:where?.toRecord()??{}).map((rows) => rows.map(Todo.fromRecord).toList());
 /// This record's sync state: its pending mutations and retained rejections. Local only.
 Future<SyncState> syncState(TodoIdentity identity) async => SyncState.fromRecord(await client.recordSyncState('Todo', identity.toRecord()));
}
class TodoTxModel extends TodoModel { final WritePort writer; TodoTxModel(this.writer) : super(writer);
 Future<void> create(Todo value) { final state=value.toRecord(); for (final key in value.identity.toRecord().keys) { state.remove(key); } return writer.direct({'model':'Todo','op':'create','identity':value.identity.toRecord(),'values':state}); }
 Future<void> update(TodoIdentity identity, TodoPatch patch) => writer.direct({'model':'Todo','op':'update','identity':identity.toRecord(),'values':patch.toRecord()});
 Future<void> delete(TodoIdentity identity) => writer.direct({'model':'Todo','op':'delete','identity':identity.toRecord()});
}
class ProjectModel { final ReadPort port; ProjectModel(this.port);
 Future<Project?> get(ProjectIdentity identity) async { final row=await port.read('Project',identity.toRecord()); return row == null ? null : Project.fromRecord(row); }
 Future<List<Project>> query({ProjectFilter? where,List<ProjectOrder> orderBy=const [],int? limit}) async => (await port.querySpec('Project',{'filter':where?.toRecord()??{},'orderBy':orderBy.map((o)=>o.toRecord()).toList(),if(limit!=null)'limit':limit})).map(Project.fromRecord).toList();
}
class ProjectLiveModel extends ProjectModel { final Client client; ProjectLiveModel(this.client) : super(client);
 Stream<List<Project>> watch({ProjectFilter? where}) => client.watch('Project', where:where?.toRecord()??{}).map((rows) => rows.map(Project.fromRecord).toList());
 /// This record's sync state: its pending mutations and retained rejections. Local only.
 Future<SyncState> syncState(ProjectIdentity identity) async => SyncState.fromRecord(await client.recordSyncState('Project', identity.toRecord()));
}
class ProjectTxModel extends ProjectModel { final WritePort writer; ProjectTxModel(this.writer) : super(writer);
 Future<void> create(Project value) { final state=value.toRecord(); for (final key in value.identity.toRecord().keys) { state.remove(key); } return writer.direct({'model':'Project','op':'create','identity':value.identity.toRecord(),'values':state}); }
 Future<void> update(ProjectIdentity identity, ProjectPatch patch) => writer.direct({'model':'Project','op':'update','identity':identity.toRecord(),'values':patch.toRecord()});
 Future<void> delete(ProjectIdentity identity) => writer.direct({'model':'Project','op':'delete','identity':identity.toRecord()});
}
/// Type-level Action contracts; runtime binding arrives with the Action engine.
enum ActionStatus { pending, succeeded, failed }
abstract interface class ActionError implements Exception { String get code; }
sealed class ActionOutcome<T> { const ActionOutcome(); }
final class ActionSuccess<T> extends ActionOutcome<T> { final T result; const ActionSuccess(this.result); }
final class ActionFailure<T> extends ActionOutcome<T> { final ActionError error; const ActionFailure(this.error); }
abstract interface class ActionCall<T> { ActionStatus get status; Future<ActionOutcome<T>> wait(); }
typedef TodoCreate = Todo;
typedef TodoDelete = TodoIdentity;
class TodoUpdate {
 final String id;
 final Present<String>? title;
 final Present<Status>? state;
 final Present<String?>? note;
 const TodoUpdate({required this.id,this.title,this.state,this.note});
}
typedef ProjectCreate = Project;
typedef ProjectDelete = ProjectIdentity;
class ProjectUpdate {
 final String tenantId;
 final String id;
 final Present<String>? title;
 const ProjectUpdate({required this.tenantId,required this.id,this.title});
}
class TodoV1Identity {
 final String id;
 const TodoV1Identity({required this.id});
}
enum AddTodoV1Status { open, closed }
class AddTodoV1TodoCreate {
 final String id;
 final String title;
 final AddTodoV1Status state;
 const AddTodoV1TodoCreate({required this.id,required this.title,required this.state});
}
class AddTodoV1TodoIdentity {
 final String id;
 const AddTodoV1TodoIdentity({required this.id});
}
class AddTodoV1TodoDelete {
 final String id;
 const AddTodoV1TodoDelete({required this.id});
}
class AddTodoV1TodoUpdate {
 final String id;
 final Present<String>? title;
 final Present<AddTodoV1Status>? state;
 const AddTodoV1TodoUpdate({required this.id,this.title,this.state});
}
class AddTodoV1PatchSlotUpdate {
 final String id;
 final Present<String>? title;
 const AddTodoV1PatchSlotUpdate({required this.id,this.title});
}
class AddTodoV1Input {
 final AddTodoV1TodoCreate todo;
 final AddTodoV1PatchSlotUpdate? patch;
 final List<AddTodoV1TodoDelete> gone;
 final AddTodoV1Status? status;
 final List<String> tags;
 const AddTodoV1Input({required this.todo,this.patch,required this.gone,required this.status,required this.tags});
}
class AddTodoV1HandlerOutput {
 final TodoV1Identity? relatedTodo;
 final List<TodoV1Identity> matches;
 final int count;
 const AddTodoV1HandlerOutput({required this.relatedTodo,required this.matches,required this.count});
}
class AddTodoPatchUpdate {
 final String id;
 final Present<String>? title;
 const AddTodoPatchUpdate({required this.id,this.title});
}
class AddTodoInput {
 final TodoCreate todo;
 final AddTodoPatchUpdate? patch;
 final List<TodoDelete> gone;
 final Status? status;
 final List<String> tags;
 const AddTodoInput({required this.todo,this.patch,required this.gone,required this.status,required this.tags});
}
class AddTodoOutput {
 final Todo todo;
 final Todo? patch;
 final List<TodoIdentity> gone;
 final Todo? relatedTodo;
 final List<Todo> matches;
 final int count;
 final Status? state;
 const AddTodoOutput({required this.todo,required this.patch,required this.gone,required this.relatedTodo,required this.matches,required this.count,required this.state});
}
class AddTodoHandlerOutput {
 final TodoIdentity? relatedTodo;
 final List<TodoIdentity> matches;
 final int count;
 final Status? state;
 const AddTodoHandlerOutput({required this.relatedTodo,required this.matches,required this.count,required this.state});
}
class DeleteTodoInput {
 final TodoDelete todo;
 const DeleteTodoInput({required this.todo});
}
class DeleteTodoOutput {
 final TodoIdentity todo;
 const DeleteTodoOutput({required this.todo});
}
typedef DeleteTodoHandlerOutput = void;
class GetTodosInput {
 const GetTodosInput();
}
class GetTodosOutput {
 final List<Todo> todos;
 const GetTodosOutput({required this.todos});
}
class GetTodosHandlerOutput {
 final List<TodoIdentity> todos;
 const GetTodosHandlerOutput({required this.todos});
}
class LinkInput {
 final ProjectCreate project;
 const LinkInput({required this.project});
}
class LinkOutput {
 final Project project;
 final Project? relatedProject;
 const LinkOutput({required this.project,required this.relatedProject});
}
class LinkHandlerOutput {
 final ProjectIdentity? relatedProject;
 const LinkHandlerOutput({required this.relatedProject});
}
class PingInput {
 const PingInput();
}
typedef PingOutput = void;
typedef PingHandlerOutput = void;
class RemoveTodoInput {
 final TodoDelete todo;
 const RemoveTodoInput({required this.todo});
}
class RemoveTodoOutput {
 final TodoIdentity todo;
 const RemoveTodoOutput({required this.todo});
}
typedef RemoveTodoHandlerOutput = void;
class SearchInput {
 final String? query;
 const SearchInput({required this.query});
}
typedef SearchOutput = void;
typedef SearchHandlerOutput = void;
class SendEmailInput {
 final String to;
 final String subject;
 final String body;
 const SendEmailInput({required this.to,required this.subject,required this.body});
}
typedef SendEmailOutput = void;
typedef SendEmailHandlerOutput = void;
class StateListInput {
 const StateListInput();
}
class StateListOutput {
 final List<Status> states;
 const StateListOutput({required this.states});
}
class StateListHandlerOutput {
 final List<Status> states;
 const StateListHandlerOutput({required this.states});
}
abstract interface class ActionTxModels {
 ActionTodoModel get todo;
 ActionProjectModel get project;
}
abstract interface class ActionModels {
 ActionTodoLiveModel get todo;
 ActionProjectLiveModel get project;
}
abstract interface class ActionTodoModel {
 Future<Todo?> get(TodoIdentity identity);
 Future<List<Todo>> query({TodoFilter? where, List<TodoOrder> orderBy = const [], int? limit});
 Future<void> create(Todo value);
 Future<void> update(TodoIdentity identity, TodoPatch patch);
 Future<void> delete(TodoIdentity identity);
}
abstract interface class ActionTodoLiveModel implements ActionTodoModel {
 Stream<List<Todo>> watch({TodoFilter? where});
}
abstract interface class ActionProjectModel {
 Future<Project?> get(ProjectIdentity identity);
 Future<List<Project>> query({ProjectFilter? where, List<ProjectOrder> orderBy = const [], int? limit});
 Future<void> create(Project value);
 Future<void> update(ProjectIdentity identity, ProjectPatch patch);
 Future<void> delete(ProjectIdentity identity);
}
abstract interface class ActionProjectLiveModel implements ActionProjectModel {
 Stream<List<Project>> watch({ProjectFilter? where});
}
abstract interface class ActionTransactionContract { ActionTxModels get models; }
abstract interface class ActionClientContract { ActionModels get models; Future<T> transaction<T>(Future<T> Function(ActionTransactionContract tx) body); ActionActionsContract get actions; }
abstract interface class ActionActionsContract { ActionDirectCallsContract get call;
 Future<ActionCall<AddTodoOutput>> addTodo({required TodoCreate todo, AddTodoPatchUpdate? patch, required List<TodoDelete> gone, required Status? status, required List<String> tags});
 Future<ActionCall<DeleteTodoOutput>> deleteTodo({required TodoDelete todo});
 Future<ActionCall<GetTodosOutput>> getTodos();
 Future<ActionCall<LinkOutput>> link({required ProjectCreate project});
 Future<ActionCall<PingOutput>> ping();
 Future<ActionCall<RemoveTodoOutput>> removeTodo({required TodoDelete todo});
 Future<ActionCall<SearchOutput>> search({required String? query});
 Future<ActionCall<SendEmailOutput>> sendEmail({required String to, required String subject, required String body});
 Future<ActionCall<StateListOutput>> stateList();
}
abstract interface class ActionDirectCallsContract {
 Future<AddTodoOutput> addTodo({required TodoCreate todo, AddTodoPatchUpdate? patch, required List<TodoDelete> gone, required Status? status, required List<String> tags});
 Future<DeleteTodoOutput> deleteTodo({required TodoDelete todo});
 Future<GetTodosOutput> getTodos();
 Future<LinkOutput> link({required ProjectCreate project});
 Future<PingOutput> ping();
 Future<RemoveTodoOutput> removeTodo({required TodoDelete todo});
 Future<SearchOutput> search({required String? query});
 Future<SendEmailOutput> sendEmail({required String to, required String subject, required String body});
 Future<StateListOutput> stateList();
}
abstract interface class ActionHandlerCall<Ctx, Args> { Ctx get ctx; Args get args; }
abstract interface class ActionHandlers<Ctx> {
 ActionAddTodoHandlers<Ctx> get addTodo;
 ActionDeleteTodoHandlers<Ctx> get deleteTodo;
 ActionGetTodosHandlers<Ctx> get getTodos;
 ActionLinkHandlers<Ctx> get link;
 ActionPingHandlers<Ctx> get ping;
 ActionRemoveTodoHandlers<Ctx> get removeTodo;
 ActionSearchHandlers<Ctx> get search;
 ActionSendEmailHandlers<Ctx> get sendEmail;
 ActionStateListHandlers<Ctx> get stateList;
}
abstract interface class ActionAddTodoHandlers<Ctx> {
 Future<AddTodoV1HandlerOutput> v1(ActionHandlerCall<Ctx, AddTodoV1Input> call);
 Future<AddTodoHandlerOutput> v2(ActionHandlerCall<Ctx, AddTodoInput> call);
}
abstract interface class ActionDeleteTodoHandlers<Ctx> {
 Future<DeleteTodoHandlerOutput> v1(ActionHandlerCall<Ctx, DeleteTodoInput> call);
}
abstract interface class ActionGetTodosHandlers<Ctx> {
 Future<GetTodosHandlerOutput> v1(ActionHandlerCall<Ctx, GetTodosInput> call);
}
abstract interface class ActionLinkHandlers<Ctx> {
 Future<LinkHandlerOutput> v1(ActionHandlerCall<Ctx, LinkInput> call);
}
abstract interface class ActionPingHandlers<Ctx> {
 Future<PingHandlerOutput> v1(ActionHandlerCall<Ctx, PingInput> call);
}
abstract interface class ActionRemoveTodoHandlers<Ctx> {
 Future<RemoveTodoHandlerOutput> v1(ActionHandlerCall<Ctx, RemoveTodoInput> call);
}
abstract interface class ActionSearchHandlers<Ctx> {
 Future<SearchHandlerOutput> v1(ActionHandlerCall<Ctx, SearchInput> call);
}
abstract interface class ActionSendEmailHandlers<Ctx> {
 Future<SendEmailHandlerOutput> v1(ActionHandlerCall<Ctx, SendEmailInput> call);
}
abstract interface class ActionStateListHandlers<Ctx> {
 Future<StateListHandlerOutput> v1(ActionHandlerCall<Ctx, StateListInput> call);
}
class Mutate { final MutatePort port; Mutate(this.port);

}
class LiveModels { final Client port; LiveModels(this.port);
 late final TodoLiveModel todo = TodoLiveModel(port);
 late final ProjectLiveModel project = ProjectLiveModel(port);
}
class TxModels { final WritePort port; TxModels(this.port);
 late final TodoTxModel todo = TodoTxModel(port);
 late final ProjectTxModel project = ProjectTxModel(port);
}
class Channels { final Client client; Channels(this.client);
 Future<void> subscribe(String channel) => client.subscribe(channel);
 Future<void> unsubscribe(String channel) => client.unsubscribe(channel);
}
class GeneratedTransaction { final Transaction transaction; late final TxModels models = TxModels(transaction); GeneratedTransaction(this.transaction); }
class GeneratedClient {
 /// The runtime handle (internal); application code uses the members below.
 final Client client; RuntimeConnection? connection; late final LiveModels models = LiveModels(client);
 /// Each mutation runs in its own local transaction and returns its ordinal.
 late final Mutate mutate = Mutate(client);
 late final Channels channels = Channels(client);
 GeneratedClient._(this.client, this.connection);
 /// Opens the local database at [path]. With a [server], the connection starts immediately and retries on its own.
 static Future<GeneratedClient> open({required String path, SyncServer? server, String? libraryPath, Map<String,dynamic>? migration, bool discardPending = false, void Function(Object)? onError, Future<void> Function()? refreshAuth}) async {
  final client = await Client.open(path:path, schema:schema, libraryPath:libraryPath, migration:migration, discardPending:discardPending);
  try {
  final connection = server == null ? null : await client.connect(server, onError:onError, refreshAuth:refreshAuth);
  return GeneratedClient._(client, connection);
  } catch (_) { try { await client.close(); } catch (_) {} rethrow; }
 }
 Future<T> transaction<T>(Future<T> Function(GeneratedTransaction tx) body) => client.transaction((tx) => body(GeneratedTransaction(tx)));
 /// This device's durable client identity.
 String get clientId => client.clientId;
 /// The client's sync state: a local snapshot, not a network probe.
 Future<Map<String,dynamic>> syncState() => client.syncState();
 /// Leave an incompatible database behind for a fresh file; refused while unsent work remains unless [discardPending].
 Future<Map<String,dynamic>> rebuild({bool discardPending = false}) => client.rebuild(discardPending: discardPending);
 /// Remove a handled rejection from the local inbox; it is not retried.
 Future<void> dismissRejection(int ordinal) => client.dismissRejection(ordinal);
 /// Remove unsent work and recompute local state; frozen work cannot be dropped.
 Future<void> drop(int ordinal) => client.drop(ordinal);
 Future<List<Map<String,dynamic>>> pendingTasks() => client.pendingTasks();
 /// Mark a prerequisite task by its opaque key: `ready`, `pending` or `failed`.
 Future<void> setReadiness(String key, String state) => client.setReadiness(key, state);
 Future<void> runPrerequisites(Map<String, Future<void> Function(Map<String,dynamic>)> handlers) => client.runPrerequisites(handlers);
 /// Start the background connection when `open` was called without a server.
 Future<RuntimeConnection> connect(SyncServer server, {void Function(Object)? onError, Future<void> Function()? refreshAuth}) async => connection = await client.connect(server, onError:onError, refreshAuth:refreshAuth);
 /// Escape hatch: an untyped structured query.
 Future<List<Map<String,dynamic>>> querySpec(String model, Map<String,dynamic> query) => client.querySpec(model, query);
 /// Escape hatch: read-only SQL over the local database.
 Future<List<Map<String,dynamic>>> readSql(String sql, {List<dynamic> parameters = const []}) => client.readSql(sql, parameters: parameters);
 Future<void> close() => client.close();
}
