[package]
name = "axton-sqlite"
version.workspace = true
edition.workspace = true
publish.workspace = true
[dependencies]
axton-core = { path = "../core" }
axton-client = { path = "../client" }
rusqlite.workspace = true
serde_json.workspace = true
[dev-dependencies]
tempfile.workspace = true
chrono.workspace = true
uuid.workspace = true
