// Generated by axton. Do not edit.
import 'dart:convert';
import 'package:axton/axton.dart';
export 'package:axton/axton.dart' show RuntimeConnection, SyncServer, ActionCall, ActionOutcome, ActionSuccess, ActionFailure, ActionStatus, ActionError;
class Present<T> { final T value; const Present(this.value); }
abstract interface class _DartActionRecord { Map<String,dynamic> toRecord(); }
final Map<String,dynamic> schema = jsonDecode(r'''{"actions":[{"input":{"enums":[],"models":[]},"inputs":[{"cardinality":"single","kind":"value","list":false,"name":"at","nullable":false,"required":true,"type":{"kind":"scalar","name":"dateTime"}}],"name":"Clock","outputEnums":[],"outputs":[{"cardinality":"single","kind":"value","name":"at","source":"handlerValue","type":{"kind":"scalar","name":"dateTime"}}],"prerequisites":[],"requirements":[],"sequence":null,"version":1},{"input":{"enums":[],"models":[]},"inputs":[],"name":"Ping","outputEnums":[],"outputs":[],"prerequisites":[],"requirements":[],"sequence":null,"version":1}],"clientPolicies":[],"enums":[],"models":[],"prerequisites":[],"requirements":[],"resultModels":[]}''') as Map<String,dynamic>;
/// Public Action lifecycle types are owned by the SDK.
class ClockInput implements _DartActionRecord {
 final DateTime at;
 const ClockInput({required this.at});
 Map<String,dynamic> toRecord() => {
 'at': _dartActionEncode(at),
 };
}
class ClockOutput implements _DartActionRecord {
 final DateTime at;
 const ClockOutput({required this.at});
 Map<String,dynamic> toRecord() => {
 'at': _dartActionEncode(at),
 };
}
class ClockHandlerOutput implements _DartActionRecord {
 final DateTime at;
 const ClockHandlerOutput({required this.at});
 Map<String,dynamic> toRecord() => {
 'at': _dartActionEncode(at),
 };
}
class PingInput implements _DartActionRecord {
 const PingInput();
 Map<String,dynamic> toRecord() => {
 };
}
typedef PingOutput = void;
typedef PingHandlerOutput = void;
abstract interface class ActionHandlerCall<Ctx, Args> { Ctx get ctx; Args get args; }
abstract interface class ActionHandlers<Ctx> {
 ActionClockHandlers<Ctx> get clock;
 ActionPingHandlers<Ctx> get ping;
}
abstract interface class ActionClockHandlers<Ctx> {
 Future<ClockHandlerOutput> v1(ActionHandlerCall<Ctx, ClockInput> call);
}
abstract interface class ActionPingHandlers<Ctx> {
 Future<PingHandlerOutput> v1(ActionHandlerCall<Ctx, PingInput> call);
}
dynamic _dartActionEncode(dynamic value) {
 if (value == null) return null;
 if (value is DateTime) return value.toUtc().toIso8601String();
 if (value is Enum) return value.name;
 if (value is List) return value.map(_dartActionEncode).toList();
 if (value is _DartActionRecord) return value.toRecord();
 return value;
}
/// Which explicit Model outputs of Clock also update local Models.
final class ClockStore extends ActionStore {
 /// Store every eligible output (the default).
 const ClockStore.all() : _mode = 0;
 /// Store no output; results are returned unchanged.
 const ClockStore.none() : _mode = 1;
 final int _mode;
 @override
 Object? toWire() => _mode == 0 ? null : false;
}
/// Which explicit Model outputs of Ping also update local Models.
final class PingStore extends ActionStore {
 /// Store every eligible output (the default).
 const PingStore.all() : _mode = 0;
 /// Store no output; results are returned unchanged.
 const PingStore.none() : _mode = 1;
 final int _mode;
 @override
 Object? toWire() => _mode == 0 ? null : false;
}
class Actions {
 final Client client; Actions(this.client); late final DirectCalls call = DirectCalls(client);
 Future<ActionCall<ClockOutput>> clock({required DateTime at, ClockStore? store}) => client.invokeAction<ClockOutput>('Clock', 1, {'at': _dartActionEncode(at)}, (value) { final row = (value as Map).cast<String,dynamic>(); return ClockOutput(at: DateTime.parse(row['at'] as String)); }, store: store);
 Future<ActionCall<PingOutput>> ping({PingStore? store}) => client.invokeAction<PingOutput>('Ping', 1, {}, (_) {}, store: store);
}
class DirectCalls {
 final Client client; DirectCalls(this.client);
 Future<ClockOutput> clock({required DateTime at, ClockStore? store}) => client.invokeDirectAction<ClockOutput>('Clock', 1, {'at': _dartActionEncode(at)}, (value) { final row = (value as Map).cast<String,dynamic>(); return ClockOutput(at: DateTime.parse(row['at'] as String)); }, store: store);
 Future<PingOutput> ping({PingStore? store}) => client.invokeDirectAction<PingOutput>('Ping', 1, {}, (_) {}, store: store);
}
class LiveModels { final Client port; LiveModels(this.port);

}
class TxModels { final WritePort port; TxModels(this.port);

}
class Channels { final Client client; Channels(this.client);
 Future<void> subscribe(String channel) => client.subscribe(channel);
 Future<void> unsubscribe(String channel) => client.unsubscribe(channel);
}
class GeneratedTransaction { final Transaction transaction; late final TxModels models = TxModels(transaction); GeneratedTransaction(this.transaction); }
class GeneratedClient {
 /// The runtime handle (internal); application code uses the members below.
 final Client client; RuntimeConnection? connection; late final LiveModels models = LiveModels(client);
 late final Channels channels = Channels(client);
 late final Actions actions = Actions(client);
 GeneratedClient._(this.client, this.connection);
 /// Opens the local database at [path]. With a [server], the connection starts immediately and retries on its own.
 static Future<GeneratedClient> open({required String path, SyncServer? server, String? libraryPath, Map<String,dynamic>? migration, bool discardPending = false, void Function(Object)? onError, Future<void> Function()? refreshAuth, Duration directTimeout = const Duration(seconds: 30)}) async {
  final client = await Client.open(path:path, schema:schema, libraryPath:libraryPath, migration:migration, discardPending:discardPending);
  try {
  final connection = server == null ? null : await client.connect(server, onError:onError, refreshAuth:refreshAuth, directTimeout:directTimeout);
  return GeneratedClient._(client, connection);
  } catch (_) { try { await client.close(); } catch (_) {} rethrow; }
 }
 Future<T> transaction<T>(Future<T> Function(GeneratedTransaction tx) body) => client.transaction((tx) => body(GeneratedTransaction(tx)));
 /// This device's durable client identity.
 String get clientId => client.clientId;
 /// The client's sync state: a local snapshot, not a network probe.
 Future<Map<String,dynamic>> syncState() => client.syncState();
 /// Leave an incompatible database behind for a fresh file; refused while unsent work remains unless [discardPending].
 Future<Map<String,dynamic>> rebuild({bool discardPending = false}) => client.rebuild(discardPending: discardPending);
 /// Remove a handled rejection from the local inbox; it is not retried.
 Future<void> dismissRejection(int ordinal) => client.dismissRejection(ordinal);
 /// Remove unsent work and recompute local state; frozen work cannot be dropped.
 Future<void> drop(int ordinal) => client.drop(ordinal);
 Future<List<Map<String,dynamic>>> pendingTasks() => client.pendingTasks();
 /// Mark a prerequisite task by its opaque key: `ready`, `pending` or `failed`.
 Future<void> setReadiness(String key, String state) => client.setReadiness(key, state);
 Future<void> runPrerequisites(Map<String, Future<void> Function(Map<String,dynamic>)> handlers) => client.runPrerequisites(handlers);
 /// Start the background connection when `open` was called without a server.
 Future<RuntimeConnection> connect(SyncServer server, {void Function(Object)? onError, Future<void> Function()? refreshAuth, Duration directTimeout = const Duration(seconds: 30)}) async => connection = await client.connect(server, onError:onError, refreshAuth:refreshAuth, directTimeout:directTimeout);
 /// Escape hatch: an untyped structured query.
 Future<List<Map<String,dynamic>>> querySpec(String model, Map<String,dynamic> query) => client.querySpec(model, query);
 /// Escape hatch: read-only SQL over the local database.
 Future<List<Map<String,dynamic>>> readSql(String sql, {List<dynamic> parameters = const []}) => client.readSql(sql, parameters: parameters);
 Future<void> close() => client.close();
}
