use serde_json::Value;
use std::fmt::Write;
fn arr<'a>(v: &'a Value, k: &str) -> &'a Vec<Value> {
    v[k].as_array().unwrap()
}
fn s<'a>(v: &'a Value, k: &str) -> &'a str {
    v[k].as_str().unwrap()
}
/// Deprecation notices are generated-code hints only ([#91](https://github.com/zanminwang/axton/issues/91)):
/// `Some(reason)` when the field, enum value or slot carries `@deprecated`.
fn deprecation<'a>(v: &'a Value, kind: &str, keys: &[(&str, &str)]) -> Option<&'a Value> {
    v["deprecations"]
        .as_array()?
        .iter()
        .find(|d| d["kind"] == kind && keys.iter().all(|(k, x)| d[*k] == *x))
        .map(|d| &d["reason"])
}
/// A JSDoc line for a deprecated member, or nothing.
fn ts_deprecated(reason: Option<&Value>) -> String {
    match reason {
        None => String::new(),
        Some(Value::String(r)) => format!(" /** @deprecated {r} */\n"),
        Some(_) => " /** @deprecated */\n".into(),
    }
}
/// A Dart `@Deprecated` annotation for a deprecated member, or nothing.
fn dart_deprecated(reason: Option<&Value>, trailing: &str) -> String {
    match reason {
        None => String::new(),
        Some(r) => format!(
            "@Deprecated('{}'){trailing}",
            r.as_str()
                .unwrap_or("")
                .replace('\\', "\\\\")
                .replace('\'', "\\'")
        ),
    }
}
fn lower(s: &str) -> String {
    let mut c = s.chars();
    format!("{}{}", c.next().unwrap().to_lowercase(), c.as_str())
}
fn ty(t: &Value, dart: bool) -> String {
    if t["kind"] == "list" {
        let e = ty(&t["element"], dart);
        return if dart {
            format!("List<{e}>")
        } else {
            format!("{e}[]")
        };
    }
    if t["kind"] == "enum" {
        return s(t, "name").into();
    }
    match s(t, "name") {
        "boolean" => {
            if dart {
                "bool"
            } else {
                "boolean"
            }
        }
        "int" => {
            if dart {
                "int"
            } else {
                "number"
            }
        }
        "float" => {
            if dart {
                "double"
            } else {
                "number"
            }
        }
        "dateTime" => {
            if dart {
                "DateTime"
            } else {
                "Date"
            }
        }
        _ => {
            if dart {
                "String"
            } else {
                "string"
            }
        }
    }
    .into()
}
fn ft(f: &Value, dart: bool) -> String {
    format!(
        "{}{}",
        ty(&f["type"], dart),
        if f["nullable"] == true {
            if dart { "?" } else { " | null" }
        } else {
            ""
        }
    )
}
fn decode(t: &Value, x: &str, dart: bool) -> String {
    if t["kind"] == "list" {
        let e = decode(&t["element"], "e", dart);
        return if dart {
            format!("({x} as List).map((e) => {e}).toList()")
        } else {
            format!("({x} as unknown[]).map(e => {e})")
        };
    }
    if t["kind"] == "enum" {
        let n = s(t, "name");
        return if dart {
            format!("{n}.values.byName({x} as String)")
        } else {
            format!("{x} as {n}")
        };
    }
    if t["name"] == "dateTime" {
        return if dart {
            format!("DateTime.parse({x} as String)")
        } else {
            format!("new Date({x} as string)")
        };
    }
    if dart && t["name"] == "float" {
        format!("({x} as num).toDouble()")
    } else {
        format!("{x} as {}", ty(t, dart))
    }
}
fn encoded(t: &Value, x: &str, dart: bool) -> String {
    if t["kind"] == "list" {
        let e = encoded(&t["element"], "e", dart);
        return if dart {
            format!("{x}.map((e) => {e}).toList()")
        } else {
            format!("{x}.map(e => {e})")
        };
    }
    if t["name"] == "dateTime" {
        return if dart {
            format!("{x}.toUtc().toIso8601String()")
        } else {
            format!("{x}.toISOString()")
        };
    }
    if dart && t["kind"] == "enum" {
        format!("{x}.name")
    } else {
        x.into()
    }
}
fn enc(f: &Value, x: &str, dart: bool) -> String {
    let e = encoded(
        &f["type"],
        &if dart && f["nullable"] == true {
            format!("{x}!")
        } else {
            x.into()
        },
        dart,
    );
    if f["nullable"] == true {
        format!("{x} == null ? null : {e}")
    } else {
        e
    }
}
pub fn typescript(v: &Value) -> String {
    let mut o = String::from(
        "// Generated by axton. Do not edit.\nimport type { ActionCall } from './client.ts';\nexport interface ReadPort { read(model:string,identity:object):Promise<Record<string,unknown>|null>; querySpec(model:string,query:object):Promise<Record<string,unknown>[]>; related(model:string,identity:object,relation:string):Promise<Record<string,unknown>|null>; referencing(model:string,identity:object,source:string,relation:string):Promise<Record<string,unknown>[]>; }\nexport interface MutatePort { mutate(value:object):Promise<number>; }\nexport interface WritePort extends ReadPort { direct(operation:object):Promise<void>; }\nexport interface LivePort extends WritePort { watch(model:string,where:Record<string,unknown>,listener:(rows:Record<string,unknown>[])=>void,onError?:(error:unknown)=>void):()=>void; syncState(model:string,identity:object):Promise<unknown>; }\nexport interface ActionPort { invokeAction<T>(name:string,version:number,args:object,decode:(value:unknown)=>T):Promise<ActionCall<T>>; invokeDirectAction<T>(name:string,version:number,args:object,decode:(value:unknown)=>T):Promise<T>; }\n",
    );
    writeln!(o, "export const schema = {} as const;", v["schema"]).unwrap();
    ts_sync_state(v, &mut o);
    for en in arr(&v["schema"], "enums") {
        for value in arr(en, "values") {
            if let Some(reason) = deprecation(
                v,
                "enumValue",
                &[("enum", s(en, "name")), ("value", value.as_str().unwrap())],
            ) {
                match reason {
                    Value::String(r) => writeln!(o, "/** @deprecated {value}: {r} */").unwrap(),
                    _ => writeln!(o, "/** @deprecated {value} */").unwrap(),
                }
            }
        }
        writeln!(
            o,
            "export type {} = {};",
            s(en, "name"),
            arr(en, "values")
                .iter()
                .map(|x| x.to_string())
                .collect::<Vec<_>>()
                .join(" | ")
        )
        .unwrap();
    }
    for m in arr(&v["schema"], "models") {
        let n = s(m, "name");
        for (suffix, filter, partial) in
            [("", 0, false), ("Identity", 1, false), ("Patch", 2, true)]
        {
            writeln!(o, "export interface {n}{suffix} {{").unwrap();
            for f in arr(m, "fields") {
                let id = arr(m, "identity").contains(&f["name"]);
                if (filter == 1 && !id) || (filter == 2 && id) {
                    continue;
                }
                o.push_str(&ts_deprecated(deprecation(
                    v,
                    "field",
                    &[("model", n), ("field", s(f, "name"))],
                )));
                writeln!(
                    o,
                    " {}{}: {};",
                    s(f, "name"),
                    if partial { "?" } else { "" },
                    ft(f, false)
                )
                .unwrap();
            }
            o.push_str("}\n");
        }
        writeln!(
            o,
            "export function decode{n}(row:Record<string,unknown>):{n} {{ return {{"
        )
        .unwrap();
        for f in arr(m, "fields") {
            let k = s(f, "name");
            let x = format!("row.{k}");
            let dec = decode(&f["type"], &x, false);
            writeln!(
                o,
                " {k}: {},",
                if f["nullable"] == true {
                    format!("{x} == null ? null : {dec}")
                } else {
                    dec
                }
            )
            .unwrap();
        }
        o.push_str("}; }\n");
        writeln!(
            o,
            "export function decode{n}Identity(row:Record<string,unknown>):{n}Identity {{ return {{"
        )
        .unwrap();
        for f in arr(m, "fields") {
            if !arr(m, "identity").contains(&f["name"]) {
                continue;
            }
            let k = s(f, "name");
            let x = format!("row.{k}");
            writeln!(o, " {k}: {},", decode(&f["type"], &x, false)).unwrap();
        }
        o.push_str("}; }\n");
        for (suffix, partial) in [
            ("", false),
            ("Identity", false),
            ("Patch", true),
            ("Where", true),
        ] {
            let input = if suffix == "Where" {
                format!("Partial<{n}>")
            } else {
                format!("{n}{suffix}")
            };
            writeln!(o,"export function encode{n}{suffix}(value:{input}):Record<string,unknown> {{ return {{").unwrap();
            for f in arr(m, "fields") {
                let id = arr(m, "identity").contains(&f["name"]);
                if (suffix == "Identity" && !id) || (suffix == "Patch" && id) {
                    continue;
                }
                let k = s(f, "name");
                let ex = enc(f, &format!("value.{k}"), false);
                if partial {
                    writeln!(o, " ...(value.{k} !== undefined ? {{ {k}: {ex} }} : {{}}),").unwrap()
                } else {
                    writeln!(o, " {k}: {ex},").unwrap()
                }
            }
            o.push_str("}; }\n");
        }
    }
    for mu in arr(v, "mutations") {
        let n = s(mu, "name");
        writeln!(o, "export interface {n}Args {{").unwrap();
        for slot in arr(mu, "slots") {
            let model = s(slot, "model");
            let input = match s(slot, "operation") {
                "create" => model.to_string(),
                "delete" => format!("{model}Identity"),
                _ => {
                    let patch = if let Some(a) = slot["allowedPatchFields"].as_array() {
                        format!(
                            "Pick<{model}Patch, {}>",
                            if a.is_empty() {
                                "never".into()
                            } else {
                                a.iter()
                                    .map(Value::to_string)
                                    .collect::<Vec<_>>()
                                    .join(" | ")
                            }
                        )
                    } else {
                        format!("{model}Patch")
                    };
                    format!("{{ identity:{model}Identity; values:{patch} }}")
                }
            };
            let card = s(slot, "cardinality");
            o.push_str(&ts_deprecated(deprecation(
                v,
                "slot",
                &[("mutation", n), ("slot", s(slot, "name"))],
            )));
            writeln!(
                o,
                " {}{}: {}{};",
                s(slot, "name"),
                if card == "optional" { "?" } else { "" },
                input,
                if card == "list" { "[]" } else { "" }
            )
            .unwrap();
        }
        o.push_str("}\n");
        writeln!(
            o,
            "export function {n}(args:{n}Args) {{ const operations:object[] = [];"
        )
        .unwrap();
        for slot in arr(mu, "slots") {
            let model = s(slot, "model");
            let key = s(slot, "name");
            let op = s(slot, "operation");
            let card = s(slot, "cardinality");
            writeln!(
                o,
                " for (const value of {}) {{",
                if card == "list" {
                    format!("args.{key}")
                } else if card == "optional" {
                    format!("args.{key} === undefined ? [] : [args.{key}]")
                } else {
                    format!("[args.{key}]")
                }
            )
            .unwrap();
            let id = if op == "update" {
                "value.identity"
            } else {
                "value"
            };
            let vals = if op == "delete" {
                String::new()
            } else if op == "update" {
                format!(", values:encode{model}Patch(value.values)")
            } else {
                format!(", values:encode{model}Patch(value)")
            };
            writeln!(o," operations.push({{ model:'{model}', op:'{op}', identity:encode{model}Identity({id}){vals} }}); }}").unwrap();
        }
        writeln!(
            o,
            " return {{name:'{n}',version:{},operations}}; }}",
            mu["version"]
        )
        .unwrap();
    }
    ts_models(v, &mut o);
    ts_actions(v, &mut o);
    o.push_str("export class Mutate { readonly port:MutatePort; constructor(port:MutatePort) { this.port=port; }\n");
    for mu in arr(v, "mutations") {
        let n = s(mu, "name");
        writeln!(
            o,
            " {}(args:{n}Args):Promise<number> {{ return this.port.mutate({n}(args)); }}",
            lower(n)
        )
        .unwrap();
    }
    o.push_str("}\n");
    let names: Vec<(String, &str)> = arr(&v["schema"], "models")
        .iter()
        .map(|m| (lower(s(m, "name")), s(m, "name")))
        .collect();
    for (suffix, port) in [("Live", "LivePort"), ("Tx", "WritePort")] {
        writeln!(
            o,
            "export interface {suffix}Models {{ {} }}",
            names
                .iter()
                .map(|(key, n)| format!("{key}:{n}{suffix}Model;"))
                .collect::<Vec<_>>()
                .join(" ")
        )
        .unwrap();
        writeln!(
            o,
            "export function {}Models(port:{port}):{suffix}Models {{ return {{ {} }}; }}",
            lower(suffix),
            names
                .iter()
                .map(|(key, n)| format!("{key}:new {n}{suffix}Model(port)"))
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();
    }
    o.push_str("export class GeneratedTransaction { readonly transaction:WritePort; readonly models:TxModels; constructor(transaction:WritePort) { this.transaction=transaction; this.models=txModels(transaction); } }\n");
    o
}
/// The typed shape of a record's sync state. Mutation names are the schema's,
/// so a pending entry's `name` is checked against them.
fn ts_sync_state(v: &Value, o: &mut String) {
    let mut names: Vec<String> = arr(v, "mutations")
        .iter()
        .map(|m| format!("'{}'", s(m, "name")))
        .collect();
    names.sort();
    names.dedup();
    let union = if names.is_empty() {
        "string".to_string()
    } else {
        names.join("|")
    };
    writeln!(o, "export type MutationName = {union};").unwrap();
    o.push_str("export interface PendingMutation { ordinal:number; name:MutationName; phase:'queued'|'frozen'; prerequisites:{key:string;state:'ready'|'pending'|'failed'}[]; diverged?:boolean; }\n");
    o.push_str(
        "export interface Rejection { ordinal:number; code:string; [key:string]:unknown; }\n",
    );
    o.push_str(
        "export interface SyncState { pending:PendingMutation[]; rejections:Rejection[]; }\n",
    );
}
fn slot_input_type(slot: &Value) -> String {
    let model = s(slot, "model");
    let one = match s(slot, "operation") {
        "create" => model.to_string(),
        "delete" => format!("{{ identity: {model}Identity }}"),
        _ => {
            let patch = match slot["allowedPatchFields"].as_array() {
                Some(a) if a.is_empty() => format!("Pick<{model}Patch, never>"),
                Some(a) => format!(
                    "Pick<{model}Patch, {}>",
                    a.iter()
                        .map(Value::to_string)
                        .collect::<Vec<_>>()
                        .join(" | ")
                ),
                None => format!("{model}Patch"),
            };
            format!("{{ identity: {model}Identity; patch: {patch} }}")
        }
    };
    match s(slot, "cardinality") {
        "list" => format!("{one}[]"),
        "optional" => format!("{one} | null"),
        _ => one,
    }
}
fn action_cardinality(base: &str, cardinality: &str) -> String {
    match cardinality {
        "optional" => format!("{base} | null"),
        "list" => format!("{base}[]"),
        _ => base.to_string(),
    }
}
fn action_input_type(input: &Value) -> String {
    if input["kind"] == "value" {
        let mut base = ty(&input["type"], false);
        if input["list"] == true {
            base.push_str("[]");
        }
        return if input["nullable"] == true {
            format!("{base} | null")
        } else {
            base
        };
    }
    let model = s(input, "model");
    let base = match s(input, "operation") {
        "create" => format!("{model}Create"),
        "delete" => format!("{model}Delete"),
        _ => {
            let keys = input["allowedPatchFields"]
                .as_array()
                .map(|fields| {
                    if fields.is_empty() {
                        "never".to_string()
                    } else {
                        fields
                            .iter()
                            .map(Value::to_string)
                            .collect::<Vec<_>>()
                            .join(" | ")
                    }
                })
                .unwrap_or_else(|| format!("keyof {model}Patch"));
            format!("{model}Update<{keys}>")
        }
    };
    action_cardinality(&base, s(input, "cardinality"))
}
fn action_output_type(output: &Value, handler: bool) -> String {
    let base = match s(output, "kind") {
        "value" => ty(&output["type"], false),
        "deleteIdentity" => format!("{}Identity", s(output, "model")),
        "model" if handler => format!("{}Identity", s(output, "model")),
        "model" => s(output, "model").to_string(),
        _ => unreachable!(),
    };
    action_cardinality(&base, s(output, "cardinality"))
}
fn action_type_name(action: &Value, latest: u64, suffix: &str) -> String {
    let name = s(action, "name");
    let version = action["version"].as_u64().unwrap();
    if version == latest {
        format!("{name}{suffix}")
    } else {
        format!("{name}V{version}{suffix}")
    }
}
fn snapshot_type(ty_value: &Value, enums: &Value) -> String {
    if ty_value["kind"] == "list" {
        return format!("{}[]", snapshot_type(&ty_value["element"], enums));
    }
    if ty_value["kind"] == "enum"
        && let Some(en) = enums
            .as_array()
            .and_then(|list| list.iter().find(|en| en["name"] == ty_value["name"]))
    {
        return arr(en, "values")
            .iter()
            .map(Value::to_string)
            .collect::<Vec<_>>()
            .join(" | ");
    }
    ty(ty_value, false)
}
fn snapshot_field_type(field: &Value, enums: &Value) -> String {
    let base = snapshot_type(&field["type"], enums);
    if field["nullable"] == true {
        format!("{base} | null")
    } else {
        base
    }
}
fn historical_action_input_type(arg: &Value, action: &Value, latest: u64) -> String {
    if action["version"].as_u64() == Some(latest) {
        return action_input_type(arg);
    }
    if arg["kind"] == "value" {
        let mut base = snapshot_type(&arg["type"], &action["input"]["enums"]);
        if arg["list"] == true {
            base = format!("({base})[]");
        }
        return if arg["nullable"] == true {
            format!("{base} | null")
        } else {
            base
        };
    }
    let prefix = action_type_name(action, latest, "");
    let model = s(arg, "model");
    let base = match s(arg, "operation") {
        "create" => format!("{prefix}{model}Create"),
        "delete" => format!("{prefix}{model}Identity"),
        _ => {
            let keys = arg["allowedPatchFields"]
                .as_array()
                .map(|fields| {
                    if fields.is_empty() {
                        "never".to_string()
                    } else {
                        fields
                            .iter()
                            .map(Value::to_string)
                            .collect::<Vec<_>>()
                            .join(" | ")
                    }
                })
                .unwrap_or_else(|| format!("keyof {prefix}{model}Patch"));
            format!("{prefix}{model}Update<{keys}>")
        }
    };
    action_cardinality(&base, s(arg, "cardinality"))
}
fn backend_action_output_type(field: &Value, action: &Value, models: &[Value]) -> String {
    let base = if field["kind"] == "value" {
        snapshot_type(&field["type"], &action["outputEnums"])
    } else {
        let model = s(field, "model");
        let read_version = field["modelReadVersion"].as_u64();
        let current = models
            .iter()
            .find(|m| m["name"] == model)
            .and_then(|m| m["version"].as_u64());
        if field["kind"] == "model" && read_version != current {
            format!("{model}V{}Identity", read_version.unwrap())
        } else {
            format!("{model}Identity")
        }
    };
    if field["kind"] == "value" && field["type"]["kind"] == "enum" && field["cardinality"] == "list"
    {
        format!("({base})[]")
    } else {
        action_cardinality(&base, s(field, "cardinality"))
    }
}
fn ts_actions(v: &Value, o: &mut String) {
    let actions = arr(v, "actions");
    if actions.is_empty() {
        o.push_str("export function makeActions(_port:ActionPort) { return { call: {} }; }\n");
        return;
    }
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        writeln!(o, "export type {n}Create = {n};").unwrap();
        writeln!(o, "export type {n}Update<K extends keyof {n}Patch = keyof {n}Patch> = {n}Identity & Partial<Pick<{n}Patch, K>>;").unwrap();
        writeln!(o, "export type {n}Delete = {n}Identity;").unwrap();
    }
    let mut latest = std::collections::BTreeMap::new();
    for action in actions {
        latest
            .entry(s(action, "name"))
            .and_modify(|n: &mut u64| *n = (*n).max(action["version"].as_u64().unwrap()))
            .or_insert(action["version"].as_u64().unwrap());
    }
    for action in actions {
        let n = s(action, "name");
        let version = latest[n];
        if action["version"].as_u64() != Some(version) {
            continue;
        }
        let input = action_type_name(action, version, "Input");
        let output = action_type_name(action, version, "Output");
        writeln!(o, "export interface {input} {{").unwrap();
        for arg in arr(action, "inputs") {
            let optional = arg["kind"] == "model" && arg["cardinality"] == "optional";
            writeln!(
                o,
                " {}{}: {};",
                s(arg, "name"),
                if optional { "?" } else { "" },
                action_input_type(arg)
            )
            .unwrap();
        }
        o.push_str("}\n");
        if arr(action, "outputs").is_empty() {
            writeln!(o, "export type {output} = void;").unwrap();
        } else {
            writeln!(o, "export interface {output} {{").unwrap();
            for field in arr(action, "outputs") {
                writeln!(
                    o,
                    " {}: {};",
                    s(field, "name"),
                    action_output_type(field, false)
                )
                .unwrap();
            }
            o.push_str("}\n");
        }
    }
    o.push_str("export interface ActionTxModels {\n");
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        writeln!(
            o,
            " {}: Pick<{n}TxModel, 'get' | 'query' | 'create' | 'update' | 'delete'>;",
            lower(n)
        )
        .unwrap();
    }
    o.push_str("}\nexport interface ActionModels {\n");
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        writeln!(
            o,
            " {}: ActionTxModels['{}'] & Pick<{n}LiveModel, 'watch'>;",
            lower(n),
            lower(n)
        )
        .unwrap();
    }
    o.push_str(
        "}\nexport interface ActionTransactionContract { readonly models: ActionTxModels; }\n",
    );
    o.push_str("export interface ActionClientContract {\n readonly models: ActionModels;\n transaction<T>(body: (tx: ActionTransactionContract) => Promise<T>): Promise<T>;\n readonly actions: {\n");
    for (n, version) in &latest {
        let action = actions
            .iter()
            .find(|a| s(a, "name") == *n && a["version"].as_u64() == Some(*version))
            .unwrap();
        let input = action_type_name(action, *version, "Input");
        let output = action_type_name(action, *version, "Output");
        writeln!(
            o,
            "  {}(args: {input}): Promise<ActionCall<{output}>>;",
            lower(n)
        )
        .unwrap();
    }
    o.push_str("  call: {\n");
    for (n, version) in &latest {
        let action = actions
            .iter()
            .find(|a| s(a, "name") == *n && a["version"].as_u64() == Some(*version))
            .unwrap();
        let input = action_type_name(action, *version, "Input");
        let output = action_type_name(action, *version, "Output");
        writeln!(o, "   {}(args: {input}): Promise<{output}>;", lower(n)).unwrap();
    }
    o.push_str("  };\n };\n}\n");
    for (name, version) in &latest {
        let action = actions
            .iter()
            .find(|a| s(a, "name") == *name && a["version"].as_u64() == Some(*version))
            .unwrap();
        writeln!(
            o,
            "function encode{name}Input(args:{name}Input):Record<string,unknown> {{ return {{"
        )
        .unwrap();
        for input in arr(action, "inputs") {
            let key = s(input, "name");
            let expr = ts_action_encode_input(input, &format!("args.{key}"));
            writeln!(o, " {key}: {expr},").unwrap();
        }
        o.push_str("}; }\n");
        if arr(action, "outputs").is_empty() {
            writeln!(
                o,
                "function decode{name}Output(_value:unknown):void {{ return undefined; }}"
            )
            .unwrap();
        } else {
            writeln!(o, "function decode{name}Output(value:unknown):{name}Output {{ const row=value as Record<string,unknown>; return {{").unwrap();
            for output in arr(action, "outputs") {
                let key = s(output, "name");
                let expr = ts_action_decode_output(output, &format!("row.{key}"));
                writeln!(o, " {key}: {expr},").unwrap();
            }
            o.push_str("}; }\n");
        }
    }
    o.push_str("export function makeActions(port:ActionPort) { return {\n");
    for (name, version) in &latest {
        writeln!(o, " {}: (args:{name}Input):Promise<ActionCall<{name}Output>> => port.invokeAction('{name}',{version},encode{name}Input(args),decode{name}Output),", lower(name)).unwrap();
    }
    o.push_str(" call: {\n");
    for (name, version) in &latest {
        writeln!(o, "  {}: (args:{name}Input):Promise<{name}Output> => port.invokeDirectAction('{name}',{version},encode{name}Input(args),decode{name}Output),", lower(name)).unwrap();
    }
    o.push_str(" }\n}; }\n");
}
fn ts_action_encode_input(input: &Value, x: &str) -> String {
    if input["kind"] == "value" {
        let ty = if input["list"] == true {
            serde_json::json!({"kind":"list","element":input["type"]})
        } else {
            input["type"].clone()
        };
        let expr = encoded(&ty, x, false);
        return if input["nullable"] == true {
            format!("{x} === null ? null : {expr}")
        } else {
            expr
        };
    }
    match s(input, "cardinality") {
        "list" => format!(
            "{x}.map(value => {})",
            ts_action_encode_model_one(input, "value")
        ),
        "optional" => format!(
            "{x} == null ? null : {}",
            ts_action_encode_model_one(input, x)
        ),
        _ => ts_action_encode_model_one(input, x),
    }
}
fn ts_action_encode_model_one(input: &Value, x: &str) -> String {
    let model = s(input, "model");
    match s(input, "operation") {
        "create" => format!("encode{model}({x})"),
        "update" => format!("{{...encode{model}Identity({x}),...encode{model}Patch({x})}}"),
        "delete" => format!("encode{model}Identity({x})"),
        _ => unreachable!(),
    }
}
fn ts_action_decode_output(output: &Value, x: &str) -> String {
    match s(output, "cardinality") {
        "list" => format!(
            "({x} as unknown[]).map(value => {})",
            ts_action_decode_one(output, "value")
        ),
        "optional" => format!("{x} == null ? null : {}", ts_action_decode_one(output, x)),
        _ => ts_action_decode_one(output, x),
    }
}
fn ts_action_decode_one(output: &Value, x: &str) -> String {
    match s(output, "kind") {
        "value" => decode(&output["type"], x, false),
        "model" => format!(
            "decode{}({x} as Record<string,unknown>)",
            s(output, "model")
        ),
        "deleteIdentity" => format!(
            "decode{}Identity({x} as Record<string,unknown>)",
            s(output, "model")
        ),
        _ => unreachable!(),
    }
}
/// Client entry point bound to the compiled schema. `runtime` is the import specifier of `@axton/client`.
pub fn client_typescript(runtime: &str) -> String {
    let mut o = String::from("// Generated by axton. Do not edit.\n");
    writeln!(o, "import {{ Client, type ClientSyncState, type Connection, type ConnectionOptions, type QuerySpec, type RebuildReport, type RecordValue, type ServerOptions }} from \"{runtime}\";").unwrap();
    writeln!(o, "export {{ ActionError, type ActionCall, type ActionOutcome, type ActionStatus, type ServerOptions, type Connection, type ConnectionOptions }} from \"{runtime}\";").unwrap();
    o.push_str("import { schema, liveModels, makeActions, GeneratedTransaction, Mutate, type LiveModels } from \"./generated.ts\";\n");
    o.push_str("export * from \"./generated.ts\";\n");
    o.push_str("export class Channels { readonly #client: Client;\n constructor(client: Client) { this.#client = client; }\n subscribe(channel: string) { return this.#client.subscribe(channel); }\n unsubscribe(channel: string) { return this.#client.unsubscribe(channel); }\n}\n");
    o.push_str("export class GeneratedClient {\n");
    o.push_str(" /** @internal The runtime handle; application code uses the members below. */\n readonly client: Client;\n connection: Connection | undefined;\n readonly models: LiveModels;\n readonly actions: ReturnType<typeof makeActions>;\n /** Each mutation runs in its own local transaction and returns its ordinal. */\n readonly mutate: Mutate;\n readonly channels: Channels;\n");
    o.push_str(" private constructor(client: Client, connection: Connection | undefined) { this.client = client; this.connection = connection; this.models = liveModels(client); this.actions = makeActions(client); this.mutate = new Mutate(client); this.channels = new Channels(client); }\n");
    o.push_str(" /** Opens the local database at `path`. With a server, the connection starts immediately and retries on its own. */\n");
    o.push_str(" static async open(options: { path: string; server?: ServerOptions; connection?: ConnectionOptions; migration?: { defaults?: RecordValue; replayPull?: boolean }; discardPending?: boolean }): Promise<GeneratedClient> {\n");
    o.push_str("  if (\"transport\" in options || \"live\" in options) throw Error(\"transport/live connection options were removed; use server: {url, token}\");\n  const client = await Client.open({ path: options.path, schema, ...(options.migration === undefined ? {} : { migration: options.migration }), ...(options.discardPending === undefined ? {} : { discardPending: options.discardPending }) });\n");
    o.push_str("  try {\n  const connection = options.server === undefined ? undefined : await client.connect(options.server, options.connection ?? {});\n");
    o.push_str("  return new GeneratedClient(client, connection);\n  } catch (error) { await client.close().catch(() => {}); throw error; }\n }\n");
    o.push_str(" transaction<T>(body: (tx: GeneratedTransaction) => Promise<T>): Promise<T> { return this.client.transaction((tx) => body(new GeneratedTransaction(tx))); }\n");
    o.push_str(" /** This device's durable client identity. */\n get clientId(): string { return this.client.clientId; }\n /** The client's sync state: a local snapshot, not a network probe. */\n syncState(): Promise<ClientSyncState> { return this.client.syncState(); }\n /** Leave an incompatible database behind for a fresh file; refused while unsent work remains unless `discardPending`. */\n rebuild(options: { discardPending?: boolean } = {}): Promise<RebuildReport> { return this.client.rebuild(options); }\n");
    o.push_str(" /** Remove a handled rejection from the local inbox; it is not retried. */\n dismissRejection(ordinal: number): Promise<void> { return this.client.dismissRejection(ordinal); }\n");
    o.push_str(" /** Remove unsent work and recompute local state; frozen work cannot be dropped. */\n drop(ordinal: number): Promise<void> { return this.client.drop(ordinal); }\n");
    o.push_str(" pendingTasks(): Promise<RecordValue[]> { return this.client.pendingTasks(); }\n");
    o.push_str(" /** Mark a prerequisite task by its opaque key. */\n setReadiness(key: string, state: \"ready\" | \"pending\" | \"failed\"): Promise<void> { return this.client.setReadiness(key, state); }\n");
    o.push_str(" runPrerequisites(handlers: Record<string, (arguments_: RecordValue) => Promise<void>>): Promise<void> { return this.client.runPrerequisites(handlers); }\n");
    o.push_str(" /** Start the background connection when `open` was called without a server. */\n async connect(server: ServerOptions, options: ConnectionOptions = {}): Promise<Connection> { this.connection = await this.client.connect(server, options); return this.connection; }\n");
    o.push_str(" /** Escape hatch: an untyped structured query. */\n querySpec(model: string, query: QuerySpec = {}): Promise<RecordValue[]> { return this.client.querySpec(model, query); }\n");
    o.push_str(" /** Escape hatch: read-only SQL over the local database. */\n readSql(sql: string, parameters: unknown[] = []): Promise<RecordValue[]> { return this.client.readSql(sql, parameters); }\n");
    o.push_str(" close() { return this.client.close(); }\n");
    o.push_str("}\n");
    o
}
/// Backend surface bound to the compiled schema. `runtime` is the import specifier of `@axton/server`.
pub fn backend_typescript(v: &Value, runtime: &str) -> String {
    let mut o = String::from("// Generated by axton. Do not edit.\n");
    let has_actions = !arr(v, "actions").is_empty();
    writeln!(o, "import {{ createBackend as createRuntimeBackend, type ActionContext, type BackendOptions, type HandlerCall, type LoaderCall, type RecordRef }} from \"{runtime}\";").unwrap();
    writeln!(o, "export {{ ActionRejected, MutationRejected, devAuth, type ActionContext, type HandlerCall, type LoaderCall, type RecordRef }} from \"{runtime}\";").unwrap();
    let models = arr(&v["schema"], "models");
    let names: Vec<String> = models
        .iter()
        .flat_map(|m| {
            let n = s(m, "name");
            [
                format!("{n} as {n}Record"),
                format!("{n}Identity"),
                format!("{n}Patch"),
            ]
        })
        .collect();
    let mut names = names;
    if has_actions {
        for en in arr(&v["schema"], "enums") {
            names.push(s(en, "name").to_string());
        }
        for m in models {
            let n = s(m, "name");
            names.extend([
                format!("{n}Create"),
                format!("{n}Update"),
                format!("{n}Delete"),
            ]);
        }
    }
    writeln!(
        o,
        "import type {{ {} }} from \"./generated.ts\";",
        names.join(", ")
    )
    .unwrap();
    writeln!(
        o,
        "import {{ {} }} from \"./generated.ts\";",
        models
            .iter()
            .map(|m| format!("encode{}Identity", s(m, "name")))
            .collect::<Vec<_>>()
            .join(", ")
    )
    .unwrap();
    for m in models {
        let n = s(m, "name");
        writeln!(o, "export type {n} = {n}Record;").unwrap();
        writeln!(o, "export type {{ {n}Identity, {n}Patch }};").unwrap();
        writeln!(o, "export function {n}(identity: {n}Identity): RecordRef {{ return {{ model: \"{n}\", identity: encode{n}Identity(identity) }}; }}").unwrap();
    }
    let mut backend = v.clone();
    if let Some(history) = v.get("backendMutations") {
        backend["mutations"] = history.clone();
        backend.as_object_mut().unwrap().remove("backendMutations");
    }
    if let Some(history) = v.get("backendModels") {
        backend["models"] = history.clone();
        backend.as_object_mut().unwrap().remove("backendModels");
    }
    writeln!(o, "const schema = {} as const;", backend).unwrap();
    let mutations = arr(&backend, "mutations");
    let latest = |name: &str| {
        mutations
            .iter()
            .filter(|m| s(m, "name") == name)
            .map(|m| m["version"].as_u64().unwrap())
            .max()
            .unwrap()
    };
    let input_name = |m: &Value| {
        let n = s(m, "name");
        let ver = m["version"].as_u64().unwrap();
        if ver == latest(n) {
            format!("{n}Input")
        } else {
            format!("{n}V{ver}Input")
        }
    };
    for m in mutations {
        writeln!(o, "export interface {} {{", input_name(m)).unwrap();
        for slot in arr(m, "slots") {
            o.push_str(&ts_deprecated(deprecation(
                v,
                "slot",
                &[("mutation", s(m, "name")), ("slot", s(slot, "name"))],
            )));
            writeln!(o, " {}: {};", s(slot, "name"), slot_input_type(slot)).unwrap();
        }
        o.push_str("}\n");
    }
    let actions = arr(v, "actions");
    let mut action_latest = std::collections::BTreeMap::new();
    for action in actions {
        action_latest
            .entry(s(action, "name"))
            .and_modify(|version: &mut u64| {
                *version = (*version).max(action["version"].as_u64().unwrap())
            })
            .or_insert(action["version"].as_u64().unwrap());
    }
    if has_actions {
        o.push_str("/** Trusted framework context and caller-supplied arguments. */\nexport type ActionHandlerCall<Tx, Args> = { ctx: ActionContext<Tx>; args: Args };\n");
        for action in actions {
            let latest = action_latest[s(action, "name")];
            if action["version"].as_u64() != Some(latest) {
                let prefix = action_type_name(action, latest, "");
                for model in arr(&action["input"], "models") {
                    let n = s(model, "name");
                    for (suffix, identity_only, patch_only) in [
                        ("Create", false, false),
                        ("Identity", true, false),
                        ("Patch", false, true),
                    ] {
                        writeln!(o, "export interface {prefix}{n}{suffix} {{").unwrap();
                        for field in arr(model, "fields") {
                            let is_id = arr(model, "identity").contains(&field["name"]);
                            if (identity_only && !is_id) || (patch_only && is_id) {
                                continue;
                            }
                            writeln!(
                                o,
                                " {}{}: {};",
                                s(field, "name"),
                                if patch_only { "?" } else { "" },
                                snapshot_field_type(field, &action["input"]["enums"])
                            )
                            .unwrap();
                        }
                        o.push_str("}\n");
                    }
                    writeln!(o, "export type {prefix}{n}Update<K extends keyof {prefix}{n}Patch = keyof {prefix}{n}Patch> = {prefix}{n}Identity & Partial<Pick<{prefix}{n}Patch, K>>;").unwrap();
                }
            }
            let input = action_type_name(action, latest, "Input");
            let output = action_type_name(action, latest, "HandlerOutput");
            writeln!(o, "export interface {input} {{").unwrap();
            for arg in arr(action, "inputs") {
                let optional = arg["kind"] == "model" && arg["cardinality"] == "optional";
                writeln!(
                    o,
                    " {}{}: {};",
                    s(arg, "name"),
                    if optional { "?" } else { "" },
                    historical_action_input_type(arg, action, latest)
                )
                .unwrap();
            }
            o.push_str("}\n");
            if arr(action, "outputs")
                .iter()
                .all(|field| field["source"].is_object())
            {
                writeln!(o, "export type {output} = void;").unwrap();
            } else {
                writeln!(o, "export interface {output} {{").unwrap();
                for field in arr(action, "outputs") {
                    if field["source"].is_object() {
                        continue;
                    }
                    writeln!(
                        o,
                        " {}: {};",
                        s(field, "name"),
                        backend_action_output_type(field, action, models)
                    )
                    .unwrap();
                }
                o.push_str("}\n");
            }
        }
    }
    // Registration groups every retained version under the mutation name; a bare function is
    // shorthand for v1 and never for the latest version ([#91](https://github.com/zanminwang/axton/issues/91)).
    o.push_str("export interface Handlers<Tx> {\n");
    let handler_context = "Tx";
    let mut emitted: Vec<&str> = vec![];
    for m in mutations {
        let n = s(m, "name");
        if emitted.contains(&n) {
            continue;
        }
        emitted.push(n);
        let mut versions: Vec<&Value> = mutations.iter().filter(|x| s(x, "name") == n).collect();
        versions.sort_by_key(|x| x["version"].as_u64().unwrap());
        let members: Vec<String> = versions
            .iter()
            .map(|x| {
                format!(
                    "v{}(call: HandlerCall<{handler_context}, {}>): Promise<void>;",
                    x["version"].as_u64().unwrap(),
                    input_name(x)
                )
            })
            .collect();
        let grouped = format!("{{ {} }}", members.join(" ").trim_end_matches(';'));
        if versions.len() == 1 && versions[0]["version"].as_u64() == Some(1) {
            writeln!(
                o,
                " {}: {grouped} | ((call: HandlerCall<{handler_context}, {}>) => Promise<void>);",
                lower(n),
                input_name(versions[0])
            )
            .unwrap();
        } else {
            writeln!(o, " {}: {grouped};", lower(n)).unwrap();
        }
    }
    if has_actions {
        for name in action_latest.keys() {
            let mut versions: Vec<&Value> =
                actions.iter().filter(|a| s(a, "name") == *name).collect();
            versions.sort_by_key(|a| a["version"].as_u64().unwrap());
            let members = versions
                .iter()
                .map(|a| {
                    let input = action_type_name(a, action_latest[name], "Input");
                    let output = action_type_name(a, action_latest[name], "HandlerOutput");
                    format!(
                        "v{}(call: ActionHandlerCall<Tx, {input}>): Promise<{output}>;",
                        a["version"].as_u64().unwrap()
                    )
                })
                .collect::<Vec<_>>()
                .join(" ");
            let grouped = format!("{{ {} }}", members.trim_end_matches(';'));
            if versions.len() == 1 && versions[0]["version"].as_u64() == Some(1) {
                let input = action_type_name(versions[0], action_latest[name], "Input");
                let output = action_type_name(versions[0], action_latest[name], "HandlerOutput");
                writeln!(o, " {}: {grouped} | ((call: ActionHandlerCall<Tx, {input}>) => Promise<{output}>);", lower(name)).unwrap();
            } else {
                writeln!(o, " {}: {grouped};", lower(name)).unwrap();
            }
        }
    }
    o.push_str("}\n");
    // Every retained model read contract: the schema's own version is the
    // latest and keeps the plain record name; an older version is its own
    // record type with the enum values of its time inline, so a loader of that
    // version cannot be typed against a value the contract never promised.
    let retained: Vec<Value> = match backend.get("models").and_then(Value::as_array) {
        Some(list) => list.clone(),
        None => models
            .iter()
            .map(|m| {
                let mut snapshot = m.clone();
                snapshot["enums"] = arr(&v["schema"], "enums")
                    .iter()
                    .filter(|e| {
                        arr(m, "fields")
                            .iter()
                            .any(|f| f["type"]["kind"] == "enum" && f["type"]["name"] == e["name"])
                    })
                    .cloned()
                    .collect();
                snapshot
            })
            .collect(),
    };
    let record_name = |contract: &Value| {
        let n = s(contract, "name");
        let current = models
            .iter()
            .find(|m| m["name"] == contract["name"])
            .map(|m| m["version"].as_u64().unwrap_or(1));
        if Some(contract["version"].as_u64().unwrap()) == current {
            n.to_string()
        } else {
            format!("{n}V{}", contract["version"])
        }
    };
    for contract in &retained {
        let name = record_name(contract);
        if name == s(contract, "name") {
            continue;
        }
        writeln!(o, "export interface {name}Identity {{").unwrap();
        for f in arr(contract, "fields") {
            if arr(contract, "identity").contains(&f["name"]) {
                writeln!(
                    o,
                    " {}: {};",
                    s(f, "name"),
                    snapshot_field_type(f, &contract["enums"])
                )
                .unwrap();
            }
        }
        o.push_str("}\n");
        writeln!(o, "export interface {name} {{").unwrap();
        for f in arr(contract, "fields") {
            let field_type = if f["type"]["kind"] == "enum" {
                let en = arr(contract, "enums")
                    .iter()
                    .find(|e| e["name"] == f["type"]["name"])
                    .expect("a retained contract carries the enums its fields use");
                format!(
                    "{}{}",
                    arr(en, "values")
                        .iter()
                        .map(Value::to_string)
                        .collect::<Vec<_>>()
                        .join(" | "),
                    if f["nullable"] == true { " | null" } else { "" }
                )
            } else {
                ft(f, false)
            };
            writeln!(o, " {}: {field_type};", s(f, "name")).unwrap();
        }
        o.push_str("}\n");
    }
    // Loader registration mirrors handlers: every retained version under the
    // model name, a bare function only for a v1-only model.
    o.push_str("export interface Loaders<Tx> {\n");
    for m in models {
        let n = s(m, "name");
        let mut versions: Vec<&Value> =
            retained.iter().filter(|c| c["name"] == m["name"]).collect();
        versions.sort_by_key(|c| c["version"].as_u64().unwrap());
        let members: Vec<String> = versions
            .iter()
            .map(|c| {
                format!(
                    "v{}(call: LoaderCall<Tx, {}Identity>): Promise<readonly ({} | null)[]>;",
                    c["version"].as_u64().unwrap(),
                    record_name(c),
                    record_name(c)
                )
            })
            .collect();
        let grouped = format!("{{ {} }}", members.join(" ").trim_end_matches(';'));
        if versions.len() == 1 && versions[0]["version"].as_u64() == Some(1) {
            writeln!(
                o,
                " {}: {grouped} | ((call: LoaderCall<Tx, {n}Identity>) => Promise<readonly ({n} | null)[]>);",
                lower(n)
            )
            .unwrap();
        } else {
            writeln!(o, " {}: {grouped};", lower(n)).unwrap();
        }
    }
    o.push_str("}\n");
    o.push_str("export type Options<Tx> = Omit<BackendOptions<Tx>, \"config\" | \"handlers\" | \"loaders\"> & { handlers: Handlers<Tx>; loaders: Loaders<Tx> };\n");
    o.push_str("export function createBackend<Tx>(options: Options<Tx>) {\n return createRuntimeBackend<Tx>({ ...options, config: schema, handlers: options.handlers as unknown as BackendOptions<Tx>[\"handlers\"], loaders: options.loaders as unknown as BackendOptions<Tx>[\"loaders\"] });\n}\n");
    o
}
fn dart_action_type(ty_value: &Value) -> String {
    ty(ty_value, true)
}
fn dart_snapshot_type(ty_value: &Value, prefix: &str, enums: &Value) -> String {
    if ty_value["kind"] == "list" {
        return format!(
            "List<{}>",
            dart_snapshot_type(&ty_value["element"], prefix, enums)
        );
    }
    if ty_value["kind"] == "enum"
        && enums
            .as_array()
            .is_some_and(|items| items.iter().any(|e| e["name"] == ty_value["name"]))
    {
        return format!("{prefix}{}", s(ty_value, "name"));
    }
    dart_action_type(ty_value)
}
fn dart_snapshot_field(field: &Value, prefix: &str, enums: &Value) -> String {
    let base = dart_snapshot_type(&field["type"], prefix, enums);
    if field["nullable"] == true {
        format!("{base}?")
    } else {
        base
    }
}
fn dart_action_cardinality(base: &str, cardinality: &str) -> String {
    match cardinality {
        "optional" => format!("{base}?"),
        "list" => format!("List<{base}>"),
        _ => base.to_string(),
    }
}
fn dart_action_input_type(
    arg: &Value,
    prefix: &str,
    restriction_prefix: &str,
    enums: &Value,
    restricted: bool,
) -> String {
    if arg["kind"] == "value" {
        let base = dart_snapshot_type(&arg["type"], prefix, enums);
        return if arg["list"] == true {
            format!("List<{base}>")
        } else if arg["nullable"] == true {
            format!("{base}?")
        } else {
            base
        };
    }
    let model = s(arg, "model");
    let base = match s(arg, "operation") {
        "create" => format!("{prefix}{model}Create"),
        "delete" => format!("{prefix}{model}Delete"),
        "update" if restricted => format!(
            "{restriction_prefix}{}{}Update",
            upper(s(arg, "name")),
            if prefix.is_empty() { "" } else { "Slot" }
        ),
        "update" => format!("{prefix}{model}Update"),
        _ => unreachable!(),
    };
    dart_action_cardinality(&base, s(arg, "cardinality"))
}
fn dart_action_output_type(
    field: &Value,
    identity: bool,
    output_prefix: &str,
    output_enums: &Value,
    models: &[Value],
) -> String {
    let base = match s(field, "kind") {
        "value" => dart_snapshot_type(&field["type"], output_prefix, output_enums),
        "deleteIdentity" => format!("{}Identity", s(field, "model")),
        "model" if identity => {
            let model = s(field, "model");
            let current = models
                .iter()
                .find(|m| m["name"] == model)
                .and_then(|m| m["version"].as_u64());
            let read = field["modelReadVersion"].as_u64();
            match read {
                Some(version) if Some(version) != current => {
                    format!("{model}V{version}Identity")
                }
                _ => format!("{model}Identity"),
            }
        }
        "model" => s(field, "model").to_string(),
        _ => unreachable!(),
    };
    dart_action_cardinality(&base, s(field, "cardinality"))
}

fn dart_data_class(o: &mut String, name: &str, fields: &[(String, String, bool)]) {
    writeln!(o, "class {name} {{").unwrap();
    for (field, ty, _) in fields {
        writeln!(o, " final {ty} {field};").unwrap();
    }
    let params = fields
        .iter()
        .map(|(field, _, required)| {
            format!("{}this.{field}", if *required { "required " } else { "" })
        })
        .collect::<Vec<_>>()
        .join(",");
    writeln!(
        o,
        " const {name}({});\n}}",
        if fields.is_empty() {
            String::new()
        } else {
            format!("{{{params}}}")
        }
    )
    .unwrap();
}
fn dart_action_update(
    o: &mut String,
    name: &str,
    model: &Value,
    allowed: Option<&Vec<Value>>,
    prefix: &str,
    enums: &Value,
) {
    let mut fields = vec![];
    for field in arr(model, "fields") {
        let key = s(field, "name");
        if arr(model, "identity").contains(&field["name"]) {
            fields.push((
                key.to_string(),
                dart_snapshot_field(field, prefix, enums),
                true,
            ));
        } else if allowed.is_none_or(|a| a.contains(&field["name"])) {
            fields.push((
                key.to_string(),
                format!("Present<{}>?", dart_snapshot_field(field, prefix, enums)),
                false,
            ));
        }
    }
    dart_data_class(o, name, &fields);
}
fn dart_actions(v: &Value, o: &mut String) {
    let actions = arr(v, "actions");
    if actions.is_empty() {
        return;
    }
    o.push_str(
        "/// Type-level Action contracts; runtime binding arrives with the Action engine.\n",
    );
    o.push_str("enum ActionStatus { pending, succeeded, failed }\nabstract interface class ActionError implements Exception { String get code; }\nsealed class ActionOutcome<T> { const ActionOutcome(); }\nfinal class ActionSuccess<T> extends ActionOutcome<T> { final T result; const ActionSuccess(this.result); }\nfinal class ActionFailure<T> extends ActionOutcome<T> { final ActionError error; const ActionFailure(this.error); }\nabstract interface class ActionCall<T> { ActionStatus get status; Future<ActionOutcome<T>> wait(); }\n");
    let models = arr(&v["schema"], "models");
    for model in models {
        let n = s(model, "name");
        writeln!(
            o,
            "typedef {n}Create = {n};\ntypedef {n}Delete = {n}Identity;"
        )
        .unwrap();
        dart_action_update(o, &format!("{n}Update"), model, None, "", &Value::Null);
    }
    let mut emitted_reads = std::collections::BTreeSet::new();
    for model in v
        .get("backendModels")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
    {
        let name = s(model, "name");
        let version = model["version"].as_u64().unwrap_or(1);
        let current = models
            .iter()
            .find(|m| m["name"] == name)
            .and_then(|m| m["version"].as_u64());
        if Some(version) == current || !emitted_reads.insert((name.to_string(), version)) {
            continue;
        }
        let fields = arr(model, "fields")
            .iter()
            .filter(|field| arr(model, "identity").contains(&field["name"]))
            .map(|field| (s(field, "name").to_string(), ft(field, true), true))
            .collect::<Vec<_>>();
        dart_data_class(o, &format!("{name}V{version}Identity"), &fields);
    }
    let mut latest = std::collections::BTreeMap::new();
    for action in actions {
        latest
            .entry(s(action, "name"))
            .and_modify(|n: &mut u64| *n = (*n).max(action["version"].as_u64().unwrap()))
            .or_insert(action["version"].as_u64().unwrap());
    }
    for action in actions {
        let name = s(action, "name");
        let is_latest = action["version"].as_u64() == Some(latest[name]);
        let prefix = action_type_name(action, latest[name], "");
        let historical = if is_latest { "" } else { prefix.as_str() };
        let input_enums = if is_latest {
            &Value::Null
        } else {
            &action["input"]["enums"]
        };
        if !is_latest {
            let mut seen = std::collections::BTreeSet::new();
            for en in input_enums.as_array().into_iter().flatten() {
                let name = s(en, "name");
                if seen.insert(name) {
                    writeln!(
                        o,
                        "enum {prefix}{name} {{ {} }}",
                        arr(en, "values")
                            .iter()
                            .map(Value::as_str)
                            .map(Option::unwrap)
                            .collect::<Vec<_>>()
                            .join(", ")
                    )
                    .unwrap();
                }
            }
            for model in arr(&action["input"], "models") {
                let model_name = s(model, "name");
                for (suffix, identity_only) in
                    [("Create", false), ("Identity", true), ("Delete", true)]
                {
                    let fields = arr(model, "fields")
                        .iter()
                        .filter(|field| {
                            !identity_only || arr(model, "identity").contains(&field["name"])
                        })
                        .map(|field| {
                            (
                                s(field, "name").to_string(),
                                dart_snapshot_field(field, &prefix, input_enums),
                                true,
                            )
                        })
                        .collect::<Vec<_>>();
                    dart_data_class(o, &format!("{prefix}{model_name}{suffix}"), &fields);
                }
                dart_action_update(
                    o,
                    &format!("{prefix}{model_name}Update"),
                    model,
                    None,
                    &prefix,
                    input_enums,
                );
            }
        }
        for arg in arr(action, "inputs") {
            if arg["kind"] == "model"
                && arg["operation"] == "update"
                && arg["allowedPatchFields"].is_array()
            {
                let model = arr(&action["input"], "models")
                    .iter()
                    .chain(models.iter())
                    .find(|m| m["name"] == arg["model"])
                    .unwrap();
                dart_action_update(
                    o,
                    &format!(
                        "{prefix}{}{}Update",
                        upper(s(arg, "name")),
                        if is_latest { "" } else { "Slot" }
                    ),
                    model,
                    arg["allowedPatchFields"].as_array(),
                    historical,
                    input_enums,
                );
            }
        }
        let inputs = arr(action, "inputs")
            .iter()
            .map(|arg| {
                let optional = arg["kind"] == "model" && arg["cardinality"] == "optional";
                (
                    s(arg, "name").to_string(),
                    dart_action_input_type(
                        arg,
                        historical,
                        &prefix,
                        input_enums,
                        arg["allowedPatchFields"].is_array(),
                    ),
                    !optional,
                )
            })
            .collect::<Vec<_>>();
        dart_data_class(o, &format!("{prefix}Input"), &inputs);
        let outputs = arr(action, "outputs");
        let output_prefix = if is_latest {
            String::new()
        } else {
            format!("{prefix}Output")
        };
        let output_enums = if is_latest {
            &Value::Null
        } else {
            &action["outputEnums"]
        };
        if !is_latest {
            let mut seen = std::collections::BTreeSet::new();
            for en in output_enums.as_array().into_iter().flatten() {
                let name = s(en, "name");
                if seen.insert(name) {
                    writeln!(
                        o,
                        "enum {output_prefix}{name} {{ {} }}",
                        arr(en, "values")
                            .iter()
                            .map(Value::as_str)
                            .map(Option::unwrap)
                            .collect::<Vec<_>>()
                            .join(", ")
                    )
                    .unwrap();
                }
            }
        }
        if is_latest {
            if outputs.is_empty() {
                writeln!(o, "typedef {prefix}Output = void;").unwrap();
            } else {
                let fields = outputs
                    .iter()
                    .map(|field| {
                        (
                            s(field, "name").to_string(),
                            dart_action_output_type(field, false, "", &Value::Null, models),
                            true,
                        )
                    })
                    .collect::<Vec<_>>();
                dart_data_class(o, &format!("{prefix}Output"), &fields);
            }
        }
        let explicit = outputs
            .iter()
            .filter(|field| !field["source"].is_object())
            .collect::<Vec<_>>();
        if explicit.is_empty() {
            writeln!(o, "typedef {prefix}HandlerOutput = void;").unwrap();
        } else {
            let fields = explicit
                .iter()
                .map(|field| {
                    (
                        s(field, "name").to_string(),
                        dart_action_output_type(field, true, &output_prefix, output_enums, models),
                        true,
                    )
                })
                .collect::<Vec<_>>();
            dart_data_class(o, &format!("{prefix}HandlerOutput"), &fields);
        }
    }
    o.push_str("abstract interface class ActionTxModels {\n");
    for model in models {
        writeln!(
            o,
            " Action{0}Model get {1};",
            s(model, "name"),
            lower(s(model, "name"))
        )
        .unwrap();
    }
    o.push_str("}\nabstract interface class ActionModels {\n");
    for model in models {
        writeln!(
            o,
            " Action{0}LiveModel get {1};",
            s(model, "name"),
            lower(s(model, "name"))
        )
        .unwrap();
    }
    o.push_str("}\n");
    for model in models {
        let n = s(model, "name");
        writeln!(o, "abstract interface class Action{n}Model {{\n Future<{n}?> get({n}Identity identity);\n Future<List<{n}>> query({{{n}Filter? where, List<{n}Order> orderBy = const [], int? limit}});\n Future<void> create({n} value);\n Future<void> update({n}Identity identity, {n}Patch patch);\n Future<void> delete({n}Identity identity);\n}}\nabstract interface class Action{n}LiveModel implements Action{n}Model {{\n Stream<List<{n}>> watch({{{n}Filter? where}});\n}}").unwrap();
    }
    o.push_str("abstract interface class ActionTransactionContract { ActionTxModels get models; }\nabstract interface class ActionClientContract { ActionModels get models; Future<T> transaction<T>(Future<T> Function(ActionTransactionContract tx) body); ActionActionsContract get actions; }\nabstract interface class ActionActionsContract { ActionDirectCallsContract get call;\n");
    for (name, version) in &latest {
        let action = actions
            .iter()
            .find(|a| s(a, "name") == *name && a["version"].as_u64() == Some(*version))
            .unwrap();
        let params = dart_action_params(action);
        writeln!(
            o,
            " Future<ActionCall<{name}Output>> {}({});",
            lower(name),
            if params.is_empty() {
                String::new()
            } else {
                format!("{{{params}}}")
            }
        )
        .unwrap();
    }
    o.push_str("}\nabstract interface class ActionDirectCallsContract {\n");
    for (name, version) in &latest {
        let action = actions
            .iter()
            .find(|a| s(a, "name") == *name && a["version"].as_u64() == Some(*version))
            .unwrap();
        let params = dart_action_params(action);
        writeln!(
            o,
            " Future<{name}Output> {}({});",
            lower(name),
            if params.is_empty() {
                String::new()
            } else {
                format!("{{{params}}}")
            }
        )
        .unwrap();
    }
    o.push_str("}\nabstract interface class ActionHandlerCall<Ctx, Args> { Ctx get ctx; Args get args; }\nabstract interface class ActionHandlers<Ctx> {\n");
    for name in latest.keys() {
        writeln!(o, " Action{}Handlers<Ctx> get {};", name, lower(name)).unwrap();
    }
    o.push_str("}\n");
    for (name, version) in &latest {
        writeln!(o, "abstract interface class Action{name}Handlers<Ctx> {{").unwrap();
        for action in actions.iter().filter(|a| s(a, "name") == *name) {
            let prefix = action_type_name(action, *version, "");
            writeln!(
                o,
                " Future<{prefix}HandlerOutput> v{}(ActionHandlerCall<Ctx, {prefix}Input> call);",
                action["version"]
            )
            .unwrap();
        }
        o.push_str("}\n");
    }
}
fn dart_action_params(action: &Value) -> String {
    arr(action, "inputs")
        .iter()
        .map(|arg| {
            let optional = arg["kind"] == "model" && arg["cardinality"] == "optional";
            format!(
                "{}{} {}",
                if optional { "" } else { "required " },
                dart_action_input_type(
                    arg,
                    "",
                    s(action, "name"),
                    &Value::Null,
                    arg["allowedPatchFields"].is_array()
                ),
                s(arg, "name")
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

pub fn dart(v: &Value) -> String {
    let mut o = String::from(
        "// Generated by axton. Do not edit.\nimport 'dart:convert';\nimport 'package:axton/axton.dart';\nexport 'package:axton/axton.dart' show RuntimeConnection, SyncServer;\nclass Present<T> { final T value; const Present(this.value); }\n",
    );
    writeln!(
        o,
        "final Map<String,dynamic> schema = jsonDecode(r'''{}''') as Map<String,dynamic>;",
        v["schema"]
    )
    .unwrap();
    for en in arr(&v["schema"], "enums") {
        writeln!(
            o,
            "enum {} {{ {} }}",
            s(en, "name"),
            arr(en, "values")
                .iter()
                .map(|x| format!(
                    "{}{}",
                    dart_deprecated(
                        deprecation(
                            v,
                            "enumValue",
                            &[("enum", s(en, "name")), ("value", x.as_str().unwrap())]
                        ),
                        " "
                    ),
                    x.as_str().unwrap()
                ))
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();
    }
    for m in arr(&v["schema"], "models") {
        let n = s(m, "name");
        for suffix in ["", "Identity", "Patch"] {
            let fields: Vec<_> = arr(m, "fields")
                .iter()
                .filter(|f| {
                    let id = arr(m, "identity").contains(&f["name"]);
                    suffix.is_empty() || (suffix == "Identity" && id) || (suffix == "Patch" && !id)
                })
                .collect();
            let patch = suffix == "Patch";
            writeln!(o, "class {n}{suffix} {{").unwrap();
            for f in &fields {
                if let Some(reason) =
                    deprecation(v, "field", &[("model", n), ("field", s(f, "name"))])
                {
                    o.push(' ');
                    o.push_str(&dart_deprecated(Some(reason), "\n"));
                }
                writeln!(
                    o,
                    " final {} {};",
                    if patch {
                        format!("Present<{}>?", ft(f, true))
                    } else {
                        ft(f, true)
                    },
                    s(f, "name")
                )
                .unwrap();
            }
            writeln!(
                o,
                " const {n}{suffix}({});",
                if fields.is_empty() {
                    String::new()
                } else {
                    format!(
                        "{{{}}}",
                        fields
                            .iter()
                            .map(|f| format!(
                                "{}this.{}",
                                if patch { "" } else { "required " },
                                s(f, "name")
                            ))
                            .collect::<Vec<_>>()
                            .join(",")
                    )
                }
            )
            .unwrap();
            writeln!(o, " Map<String,dynamic> toRecord() => {{").unwrap();
            for f in &fields {
                let k = s(f, "name");
                let x = if patch {
                    format!("{k}!.value")
                } else {
                    k.into()
                };
                writeln!(
                    o,
                    " {}'{k}': {},",
                    if patch {
                        format!("if ({k} != null) ")
                    } else {
                        String::new()
                    },
                    enc(f, &x, true)
                )
                .unwrap();
            }
            o.push_str(" };\n");
            if !patch {
                writeln!(
                    o,
                    " factory {n}{suffix}.fromRecord(Map<String,dynamic> row) => {n}{suffix}("
                )
                .unwrap();
                for f in &fields {
                    let k = s(f, "name");
                    let x = format!("row['{k}']");
                    let d = decode(&f["type"], &x, true);
                    writeln!(
                        o,
                        " {k}: {},",
                        if f["nullable"] == true {
                            format!("{x} == null ? null : {d}")
                        } else {
                            d
                        }
                    )
                    .unwrap();
                }
                o.push_str(" );\n");
            }
            if suffix.is_empty() {
                writeln!(
                    o,
                    " {n}Identity get identity => {n}Identity({});",
                    arr(m, "identity")
                        .iter()
                        .map(|x| format!("{0}: {0}", x.as_str().unwrap()))
                        .collect::<Vec<_>>()
                        .join(",")
                )
                .unwrap();
            }
            o.push_str("}\n");
        }
    }
    let mut mutate_methods = vec![];
    for mu in arr(v, "mutations") {
        let n = s(mu, "name");
        let mut params = vec![];
        let mut keys = vec![];
        for slot in arr(mu, "slots") {
            let model = s(slot, "model");
            let key = s(slot, "name");
            keys.push(key);
            let op = s(slot, "operation");
            let base = if op == "update" {
                let mut chars = key.chars();
                let slot_type =
                    format!("{}{}", chars.next().unwrap().to_uppercase(), chars.as_str());
                let input = format!("{n}{slot_type}Update");
                let m = arr(&v["schema"], "models")
                    .iter()
                    .find(|m| m["name"] == model)
                    .unwrap();
                let fields: Vec<_> = arr(m, "fields")
                    .iter()
                    .filter(|f| {
                        !arr(m, "identity").contains(&f["name"])
                            && slot["allowedPatchFields"]
                                .as_array()
                                .is_none_or(|a| a.contains(&f["name"]))
                    })
                    .collect();
                writeln!(o, "class {input} {{\n final {model}Identity identity;").unwrap();
                for f in &fields {
                    if let Some(reason) =
                        deprecation(v, "field", &[("model", model), ("field", s(f, "name"))])
                    {
                        o.push(' ');
                        o.push_str(&dart_deprecated(Some(reason), "\n"));
                    }
                    writeln!(o, " final Present<{}>? {};", ft(f, true), s(f, "name")).unwrap();
                }
                writeln!(
                    o,
                    " const {input}({{required this.identity,{}}});",
                    fields
                        .iter()
                        .map(|f| format!("this.{}", s(f, "name")))
                        .collect::<Vec<_>>()
                        .join(",")
                )
                .unwrap();
                o.push_str(" Map<String,dynamic> toRecord() => {\n");
                for f in fields {
                    let k = s(f, "name");
                    writeln!(
                        o,
                        " if ({k} != null) '{k}': {},",
                        enc(f, &format!("{k}!.value"), true)
                    )
                    .unwrap();
                }
                o.push_str(" };\n}\n");
                input
            } else if op == "delete" {
                format!("{model}Identity")
            } else {
                model.to_string()
            };
            let card = s(slot, "cardinality");
            let mark = dart_deprecated(
                deprecation(v, "slot", &[("mutation", n), ("slot", key)]),
                " ",
            );
            params.push(if card == "list" {
                format!("{mark}required List<{base}> {key}")
            } else if card == "optional" {
                format!("{mark}{base}? {key}")
            } else {
                format!("{mark}required {base} {key}")
            });
        }
        writeln!(
            o,
            "Map<String,dynamic> {}({{{}}}) {{ final operations=<Map<String,dynamic>>[];",
            lower(n),
            params.join(",")
        )
        .unwrap();
        mutate_methods.push(format!(
            " Future<int> {0}({{{1}}}) => port.mutate(_{0}({2}));",
            lower(n),
            params.join(","),
            keys.iter()
                .map(|k| format!("{k}:{k}"))
                .collect::<Vec<_>>()
                .join(",")
        ));
        for slot in arr(mu, "slots") {
            let model = s(slot, "model");
            let key = s(slot, "name");
            let op = s(slot, "operation");
            let card = s(slot, "cardinality");
            let vals = if card == "list" {
                key.to_string()
            } else if card == "optional" {
                format!("[{key}].nonNulls")
            } else {
                format!("[{key}]")
            };
            let identity = if op == "delete" {
                "value.toRecord()"
            } else {
                "value.identity.toRecord()"
            };
            writeln!(o, " for (final value in {vals}) {{").unwrap();
            if op == "create" {
                writeln!(o," final state=value.toRecord(); for (final key in value.identity.toRecord().keys) {{ state.remove(key); }}").unwrap();
            }
            writeln!(
                o,
                " operations.add({{'model':'{model}','op':'{op}','identity':{identity}{}}}); }}",
                if op == "delete" {
                    String::new()
                } else if op == "create" {
                    ",'values':state".into()
                } else {
                    ",'values':value.toRecord()".into()
                }
            )
            .unwrap();
        }
        writeln!(
            o,
            " return {{'name':'{n}','version':{},'operations':operations}}; }}\nfinal _{} = {};",
            mu["version"],
            lower(n),
            lower(n)
        )
        .unwrap();
    }
    dart_query_types(v, &mut o);
    dart_models(v, &mut o);
    dart_actions(v, &mut o);
    writeln!(
        o,
        "class Mutate {{ final MutatePort port; Mutate(this.port);\n{}\n}}",
        mutate_methods.join("\n")
    )
    .unwrap();
    let names: Vec<(String, &str)> = arr(&v["schema"], "models")
        .iter()
        .map(|m| (lower(s(m, "name")), s(m, "name")))
        .collect();
    for (suffix, port) in [("Live", "Client"), ("Tx", "WritePort")] {
        writeln!(
            o,
            "class {suffix}Models {{ final {port} port; {suffix}Models(this.port);\n{}\n}}",
            names
                .iter()
                .map(|(key, n)| format!(
                    " late final {n}{suffix}Model {key} = {n}{suffix}Model(port);"
                ))
                .collect::<Vec<_>>()
                .join("\n")
        )
        .unwrap();
    }
    o.push_str("class Channels { final Client client; Channels(this.client);\n Future<void> subscribe(String channel) => client.subscribe(channel);\n Future<void> unsubscribe(String channel) => client.unsubscribe(channel);\n}\n");
    o.push_str("class GeneratedTransaction { final Transaction transaction; late final TxModels models = TxModels(transaction); GeneratedTransaction(this.transaction); }\n");
    o.push_str("class GeneratedClient {\n /// The runtime handle (internal); application code uses the members below.\n final Client client; RuntimeConnection? connection; late final LiveModels models = LiveModels(client);\n /// Each mutation runs in its own local transaction and returns its ordinal.\n late final Mutate mutate = Mutate(client);\n late final Channels channels = Channels(client);\n GeneratedClient._(this.client, this.connection);\n");
    o.push_str(" /// Opens the local database at [path]. With a [server], the connection starts immediately and retries on its own.\n");
    o.push_str(" static Future<GeneratedClient> open({required String path, SyncServer? server, String? libraryPath, Map<String,dynamic>? migration, bool discardPending = false, void Function(Object)? onError, Future<void> Function()? refreshAuth}) async {\n  final client = await Client.open(path:path, schema:schema, libraryPath:libraryPath, migration:migration, discardPending:discardPending);\n  try {\n  final connection = server == null ? null : await client.connect(server, onError:onError, refreshAuth:refreshAuth);\n  return GeneratedClient._(client, connection);\n  } catch (_) { try { await client.close(); } catch (_) {} rethrow; }\n }\n");
    o.push_str(" Future<T> transaction<T>(Future<T> Function(GeneratedTransaction tx) body) => client.transaction((tx) => body(GeneratedTransaction(tx)));\n /// This device's durable client identity.\n String get clientId => client.clientId;\n /// The client's sync state: a local snapshot, not a network probe.\n Future<Map<String,dynamic>> syncState() => client.syncState();\n /// Leave an incompatible database behind for a fresh file; refused while unsent work remains unless [discardPending].\n Future<Map<String,dynamic>> rebuild({bool discardPending = false}) => client.rebuild(discardPending: discardPending);\n /// Remove a handled rejection from the local inbox; it is not retried.\n Future<void> dismissRejection(int ordinal) => client.dismissRejection(ordinal);\n /// Remove unsent work and recompute local state; frozen work cannot be dropped.\n Future<void> drop(int ordinal) => client.drop(ordinal);\n Future<List<Map<String,dynamic>>> pendingTasks() => client.pendingTasks();\n /// Mark a prerequisite task by its opaque key: `ready`, `pending` or `failed`.\n Future<void> setReadiness(String key, String state) => client.setReadiness(key, state);\n Future<void> runPrerequisites(Map<String, Future<void> Function(Map<String,dynamic>)> handlers) => client.runPrerequisites(handlers);\n /// Start the background connection when `open` was called without a server.\n Future<RuntimeConnection> connect(SyncServer server, {void Function(Object)? onError, Future<void> Function()? refreshAuth}) async => connection = await client.connect(server, onError:onError, refreshAuth:refreshAuth);\n /// Escape hatch: an untyped structured query.\n Future<List<Map<String,dynamic>>> querySpec(String model, Map<String,dynamic> query) => client.querySpec(model, query);\n /// Escape hatch: read-only SQL over the local database.\n Future<List<Map<String,dynamic>>> readSql(String sql, {List<dynamic> parameters = const []}) => client.readSql(sql, parameters: parameters);\n Future<void> close() => client.close();\n}\n");
    o
}
fn upper(name: &str) -> String {
    let mut chars = name.chars();
    format!("{}{}", chars.next().unwrap().to_uppercase(), chars.as_str())
}
fn ts_models(v: &Value, o: &mut String) {
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        let scalar = arr(model, "fields")
            .iter()
            .filter(|f| f["type"]["kind"] == "scalar")
            .map(|f| format!("'{}'", s(f, "name")))
            .collect::<Vec<_>>()
            .join(" | ");
        let scalar = if scalar.is_empty() {
            "never".into()
        } else {
            scalar
        };
        let lists = arr(model, "fields")
            .iter()
            .filter(|f| f["type"]["kind"] == "list")
            .map(|f| format!("'{}'", s(f, "name")))
            .collect::<Vec<_>>()
            .join(" | ");
        let filter = if lists.is_empty() {
            format!("Partial<{n}>")
        } else {
            format!("Partial<Omit<{n}, {lists}>>")
        };
        writeln!(
            o,
            "export class {n}Model<P extends ReadPort=ReadPort> {{ readonly port:P; constructor(port:P) {{ this.port=port; }}"
        )
        .unwrap();
        writeln!(o, " async get(identity:{n}Identity):Promise<{n}|null> {{ const row=await this.port.read('{n}',encode{n}Identity(identity)); return row===null ? null : decode{n}(row); }}").unwrap();
        writeln!(o, " async query(options:{{where?:{filter};orderBy?:{{field:{scalar};direction:'ascending'|'descending'}}[];limit?:number}}={{}}):Promise<{n}[]> {{ return (await this.port.querySpec('{n}',{{filter:encode{n}Where(options.where??{{}}),orderBy:options.orderBy??[],...(options.limit===undefined?{{}}:{{limit:options.limit}})}})).map(decode{n}); }}").unwrap();
        for relation in arr(model, "relations") {
            let target = s(relation, "target");
            let name = s(relation, "name");
            writeln!(o, " async {name}(identity:{n}Identity):Promise<{target}|null> {{ const row=await this.port.related('{n}',encode{n}Identity(identity),'{name}'); return row===null?null:decode{target}(row); }}").unwrap();
        }
        for inverse in arr(v, "inverses").iter().filter(|i| i["model"] == n) {
            let target = s(inverse, "target");
            let name = s(inverse, "name");
            let reference = s(inverse, "reference");
            if inverse["list"] != true {
                writeln!(o, " async {name}(identity:{n}Identity):Promise<{target}|null> {{ const rows=await this.port.referencing('{n}',encode{n}Identity(identity),'{target}','{reference}');if(rows.length>1)throw Error('singular inverse has multiple rows');return rows.length===0?null:decode{target}(rows[0]!); }}").unwrap();
            } else {
                writeln!(o, " async {name}(identity:{n}Identity):Promise<{target}[]> {{ return (await this.port.referencing('{n}',encode{n}Identity(identity),'{target}','{reference}')).map(decode{target}); }}").unwrap();
            }
        }
        o.push_str("}\n");
        writeln!(o, "export class {n}TxModel<P extends WritePort=WritePort> extends {n}Model<P> {{\n create(value:{n}):Promise<void> {{ return this.port.direct({{model:'{n}',op:'create',identity:encode{n}Identity(value),values:encode{n}Patch(value)}}); }}\n update(identity:{n}Identity, patch:{n}Patch):Promise<void> {{ return this.port.direct({{model:'{n}',op:'update',identity:encode{n}Identity(identity),values:encode{n}Patch(patch)}}); }}\n delete(identity:{n}Identity):Promise<void> {{ return this.port.direct({{model:'{n}',op:'delete',identity:encode{n}Identity(identity)}}); }}\n}}").unwrap();
        writeln!(o, "export class {n}LiveModel extends {n}TxModel<LivePort> {{\n watch(options:{{where?:{filter}}}, listener:(rows:{n}[])=>void, onError?:(error:unknown)=>void):()=>void {{ return this.port.watch('{n}',encode{n}Where(options.where??{{}}),(rows)=>listener(rows.map(decode{n})),onError); }}\n /** This record's sync state: its pending mutations and retained rejections. Local only. */\n async syncState(identity:{n}Identity):Promise<SyncState> {{ return (await this.port.syncState('{n}',encode{n}Identity(identity))) as SyncState; }}\n}}").unwrap();
    }
}
fn dart_query_types(v: &Value, o: &mut String) {
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        let fields = arr(model, "fields")
            .iter()
            .filter(|f| f["type"]["kind"] != "list")
            .collect::<Vec<_>>();
        writeln!(o, "class {n}Filter {{").unwrap();
        for f in &fields {
            if let Some(reason) = deprecation(v, "field", &[("model", n), ("field", s(f, "name"))])
            {
                o.push(' ');
                o.push_str(&dart_deprecated(Some(reason), "\n"));
            }
            writeln!(o, " final Present<{}>? {};", ft(f, true), s(f, "name")).unwrap();
        }
        writeln!(
            o,
            " const {n}Filter({{{}}});\n Map<String,dynamic> toRecord()=>{{",
            fields
                .iter()
                .map(|f| format!("this.{}", s(f, "name")))
                .collect::<Vec<_>>()
                .join(",")
        )
        .unwrap();
        for f in &fields {
            let name = s(f, "name");
            writeln!(
                o,
                " if({name}!=null)'{name}':{},",
                enc(f, &format!("{name}!.value"), true)
            )
            .unwrap();
        }
        o.push_str("};\n}\n");
        let scalar = fields
            .iter()
            .filter(|f| f["type"]["kind"] == "scalar")
            .map(|f| format!("by{}('{}')", upper(s(f, "name")), s(f, "name")))
            .collect::<Vec<_>>()
            .join(",");
        writeln!(o,"enum {n}OrderField {{{scalar}; final String wireName; const {n}OrderField(this.wireName);}}\nclass {n}Order {{ final {n}OrderField field; final bool descending; const {n}Order(this.field,{{this.descending=false}}); Map<String,dynamic> toRecord()=>{{'field':field.wireName,'direction':descending?'descending':'ascending'}}; }}").unwrap();
    }
}
fn dart_models(v: &Value, o: &mut String) {
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        writeln!(
            o,
            "class {n}Model {{ final ReadPort port; {n}Model(this.port);"
        )
        .unwrap();
        writeln!(o, " Future<{n}?> get({n}Identity identity) async {{ final row=await port.read('{n}',identity.toRecord()); return row == null ? null : {n}.fromRecord(row); }}").unwrap();
        writeln!(o, " Future<List<{n}>> query({{{n}Filter? where,List<{n}Order> orderBy=const [],int? limit}}) async => (await port.querySpec('{n}',{{'filter':where?.toRecord()??{{}},'orderBy':orderBy.map((o)=>o.toRecord()).toList(),if(limit!=null)'limit':limit}})).map({n}.fromRecord).toList();").unwrap();
        for relation in arr(model, "relations") {
            let target = s(relation, "target");
            let name = s(relation, "name");
            writeln!(o, " Future<{target}?> {name}({n}Identity identity) async {{ final row=await port.related('{n}',identity.toRecord(),'{name}');return row==null?null:{target}.fromRecord(row); }}").unwrap();
        }
        for inverse in arr(v, "inverses").iter().filter(|i| i["model"] == n) {
            let target = s(inverse, "target");
            let name = s(inverse, "name");
            let reference = s(inverse, "reference");
            if inverse["list"] != true {
                writeln!(o, " Future<{target}?> {name}({n}Identity identity) async {{final rows=await port.referencing('{n}',identity.toRecord(),'{target}','{reference}');if(rows.length>1)throw StateError('singular inverse has multiple rows');return rows.isEmpty?null:{target}.fromRecord(rows.single);}}").unwrap();
            } else {
                writeln!(o, " Future<List<{target}>> {name}({n}Identity identity) async => (await port.referencing('{n}',identity.toRecord(),'{target}','{reference}')).map({target}.fromRecord).toList();").unwrap();
            }
        }
        o.push_str("}\n");
        writeln!(o, "class {n}LiveModel extends {n}Model {{ final Client client; {n}LiveModel(this.client) : super(client);\n Stream<List<{n}>> watch({{{n}Filter? where}}) => client.watch('{n}', where:where?.toRecord()??{{}}).map((rows) => rows.map({n}.fromRecord).toList());\n /// This record's sync state: its pending mutations and retained rejections. Local only.\n Future<SyncState> syncState({n}Identity identity) async => SyncState.fromRecord(await client.recordSyncState('{n}', identity.toRecord()));\n}}").unwrap();
        writeln!(o, "class {n}TxModel extends {n}Model {{ final WritePort writer; {n}TxModel(this.writer) : super(writer);\n Future<void> create({n} value) {{ final state=value.toRecord(); for (final key in value.identity.toRecord().keys) {{ state.remove(key); }} return writer.direct({{'model':'{n}','op':'create','identity':value.identity.toRecord(),'values':state}}); }}\n Future<void> update({n}Identity identity, {n}Patch patch) => writer.direct({{'model':'{n}','op':'update','identity':identity.toRecord(),'values':patch.toRecord()}});\n Future<void> delete({n}Identity identity) => writer.direct({{'model':'{n}','op':'delete','identity':identity.toRecord()}});\n}}").unwrap();
    }
}
